import { cn } from "#/ui/cn.ts";

/**
 * The legacy site's colour blobs.
 *
 * Each is a closed loop, generated by walking a circle and varying the radius, then fitting a
 * smooth curve through the result — so there is no seam to kink and every edge is round. They are
 * meant to be positioned so a good part of them hangs off the side of the page: the viewport clips
 * that off into the single straight edge the legacy shapes had, and nothing else is ever cut.
 *
 * Drawing them open, with a hand-written return curve back to the edge, is what produced both
 * earlier problems — the kink at the join, and silhouettes that could only ever be bulges.
 */

const blobs = {
  /** Broad and softly triangular, the heaviest of the set. */
  boulder:
    "M340 40C388 42 476 184 509 242C542 302 609 442 587 482C564 523 408 544 340 545C272 546 106 532 80 490C55 448 115 290 149 230C184 170 292 38 340 40Z",
  /** Wide and low, with a shallow dip along one side. */
  puddle:
    "M340 110C391 101 551 117 575 153C599 189 535 321 520 381C506 441 502 582 466 601C430 621 305 555 249 529C193 503 55 448 48 407C40 366 152 261 191 222C230 182 289 119 340 110Z",
  /** Leans to one side, wider at the top than the bottom. */
  bean: "M340 40C389 40 487 175 522 235C557 295 624 453 600 490C576 527 408 511 340 510C272 509 114 522 89 485C64 448 120 292 154 232C187 173 291 40 340 40Z",
  /** Squarer, with a pinched waist — the most characterful. */
  pebble:
    "M340 80C393 77 528 93 552 128C576 163 521 285 520 340C519 395 566 515 542 542C518 568 395 539 340 540C285 541 151 579 128 552C105 525 162 393 165 340C168 287 129 187 153 153C176 118 287 83 340 80Z",
  /** Angular for a blob: a long straight-ish run into a tight corner. */
  drift:
    "M340 40C387 46 453 173 489 222C524 270 614 357 608 401C602 445 495 524 442 552C389 580 246 633 210 610C173 587 179 437 169 379C160 321 114 223 137 178C159 133 293 34 340 40Z",
} as const;

/** Every blob is drawn in the same square box, so callers can size them with a single utility. */
const BLOB_VIEW_BOX = "0 0 680 680";

const tones = {
  green: "var(--color-primary-pale)",
  blue: "var(--color-accent-pale)",
} as const;

/**
 * One blob. The caller positions and sizes it, and is expected to pull it past the edge of the page
 * with a negative inset; the layout's `overflow-x-clip` does the cutting.
 *
 * The host section needs `relative isolate`, so the negative layer stays inside it instead of
 * dropping behind the page background. Keep the blob within that section's height too: anything
 * that overhangs vertically is cut off square where the next section's background begins.
 */
export const EdgeBlob = ({
  blob,
  className,
  rotate = 0,
  tone,
}: {
  blob: keyof typeof blobs;
  className?: string;
  /** Degrees. Reuses one silhouette at several placements without it reading as a repeat. */
  rotate?: number;
  tone: keyof typeof tones;
}) => (
  // The drift animation owns the outer element's transform, so the rotation needs its own element
  // or the two overwrite each other.
  <div aria-hidden className={cn("drift pointer-events-none absolute -z-10 opacity-45", className)}>
    <div className="h-full w-full" style={{ transform: `rotate(${rotate}deg)` }}>
      <svg
        aria-hidden
        className="h-full w-full"
        viewBox={BLOB_VIEW_BOX}
        xmlns="http://www.w3.org/2000/svg"
      >
        <path d={blobs[blob]} fill={tones[tone]} />
      </svg>
    </div>
  </div>
);
