import type { Salutation } from "@stu/lib";
import { sql } from "@stu/db";
import { db } from "@stu/db/client";
import { Persons } from "@stu/db/schema";
import { getTeachers } from "@stu/external-api";

const FISTNAME_SALUTATION_MAP: Record<string, Salutation> = {
  Afrodite: "Frau",
  Alexander: "Herr",
  Andrea: "Frau",
  Anke: "Frau",
  "Ann-Kathrin": "Frau",
  Anna: "Frau",
  Anne: "Frau",
  Arend: "Herr",
  Arvid: "Herr",
  Beate: "Frau",
  Bernd: "Herr",
  Bianca: "Frau",
  Birte: "Frau",
  Brigitte: "Frau",
  Carmen: "Frau",
  Carsten: "Herr",
  Catharina: "Frau",
  Christian: "Herr",
  Claudia: "Frau",
  Corinna: "Frau",
  Daniel: "Herr",
  David: "Herr",
  Derek: "Herr",
  Domenik: "Herr",
  Dominik: "Herr",
  Dorothea: "Frau",
  Dorothee: "Frau",
  Dörte: "Frau",
  Eren: "Herr",
  Eva: "Frau",
  Felix: "Herr",
  Fiona: "Frau",
  Frank: "Herr",
  Frederic: "Herr",
  Frederik: "Herr",
  Georg: "Herr",
  Hagen: "Herr",
  Hauke: "Herr",
  Imke: "Frau",
  Inken: "Frau",
  Irma: "Frau",
  Ivonne: "Frau",
  Jan: "Herr",
  Janika: "Frau",
  Janine: "Frau",
  Jasper: "Herr",
  Jendrik: "Herr",
  Jennifer: "Frau",
  Jens: "Herr",
  Julia: "Frau",
  Julian: "Herr",
  Kathrin: "Frau",
  Katja: "Frau",
  Katrin: "Frau",
  Keno: "Herr",
  Kerstin: "Frau",
  Kirsten: "Frau",
  Kristina: "Frau",
  Leif: "Herr",
  Linda: "Frau",
  Lioba: "Frau",
  Lisa: "Frau",
  Lukas: "Herr",
  Marcus: "Herr",
  Mario: "Herr",
  Marion: "Frau",
  Marita: "Frau",
  Markus: "Herr",
  Martin: "Herr",
  Maximilian: "Herr",
  Melanie: "Frau",
  Melinda: "Frau",
  Michael: "Herr",
  Michelle: "Frau",
  Moritz: "Herr",
  Natalia: "Frau",
  Nathalie: "Frau",
  Nesli: "Frau",
  Nico: "Herr",
  Paurnima: "Frau",
  Rebecca: "Frau",
  Roman: "Herr",
  Sabine: "Frau",
  Sabrina: "Frau",
  Sandra: "Frau",
  Sebastian: "Herr",
  Simon: "Herr",
  Sonja: "Frau",
  Susanne: "Frau",
  Sybille: "Frau",
  Tanja: "Frau",
  Tatjana: "Frau",
  Thomas: "Herr",
  Thorge: "Herr",
  Thorsten: "Herr",
  Tobias: "Herr",
  Tom: "Herr",
  Veronica: "Frau",
  Viktor: "Herr",
  Viviane: "Frau",
  Wiebke: "Frau",
  Wolfgang: "Herr",
};

export const importTeachers = async () => {
  const teachers = getTeachers();

  await db
    .insert(Persons)
    .values(
      teachers.map((teacher) => ({
        name: `${teacher.firstName} ${teacher.lastName}`,
        abbrv: teacher.abbrv,
        salutation:
          FISTNAME_SALUTATION_MAP[teacher.firstName.split(" ")[0] ?? ""],
      })),
    )
    .onConflictDoUpdate({
      target: [Persons.abbrv],
      set: {
        name: sql.raw(`excluded.${Persons.name.name}`), // excluded is a special table that contains the conflicting row
        salutation: sql.raw(`excluded.${Persons.salutation.name}`),
      },
    });
};
