// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXJKbKhUmNUx19tuHQ9xsKY_R2pt0hnDE',
    appId: '1:580059450872:android:07d539c7c136d64989da0d',
    messagingSenderId: '580059450872',
    projectId: 'de-haukeschnau-classmate',
    storageBucket: 'de-haukeschnau-classmate.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkzmdb7KPwNvd4RN5_sB7vY0V4cA1O_r8',
    appId: '1:580059450872:ios:581d78ec32aa175989da0d',
    messagingSenderId: '580059450872',
    projectId: 'de-haukeschnau-classmate',
    storageBucket: 'de-haukeschnau-classmate.appspot.com',
    iosClientId: '580059450872-okv7k9tc2nvpv2uj9htfagk2qeo6la55.apps.googleusercontent.com',
    iosBundleId: 'de.haukeschnau.classMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkzmdb7KPwNvd4RN5_sB7vY0V4cA1O_r8',
    appId: '1:580059450872:ios:581d78ec32aa175989da0d',
    messagingSenderId: '580059450872',
    projectId: 'de-haukeschnau-classmate',
    storageBucket: 'de-haukeschnau-classmate.appspot.com',
    iosClientId: '580059450872-okv7k9tc2nvpv2uj9htfagk2qeo6la55.apps.googleusercontent.com',
    iosBundleId: 'de.haukeschnau.classMate',
  );
}
