// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlEwdSTk32E17GDxe7ySjXUWrqnEo2H0Q',
    appId: '1:523838006351:android:63536196a070d63d07363a',
    messagingSenderId: '523838006351',
    projectId: 'studienbuch-3aa23',
    storageBucket: 'studienbuch-3aa23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmf6vl0DYVbQ8t3oHdUoBukp4Pr6x5uaE',
    appId: '1:523838006351:ios:17fc7a92c4598cd607363a',
    messagingSenderId: '523838006351',
    projectId: 'studienbuch-3aa23',
    storageBucket: 'studienbuch-3aa23.appspot.com',
    iosBundleId: 'de.haukeschnau.classMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmf6vl0DYVbQ8t3oHdUoBukp4Pr6x5uaE',
    appId: '1:523838006351:ios:17fc7a92c4598cd607363a',
    messagingSenderId: '523838006351',
    projectId: 'studienbuch-3aa23',
    storageBucket: 'studienbuch-3aa23.appspot.com',
    iosBundleId: 'de.haukeschnau.classMate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvK_ePStQMuBpyHKe1AH6CxSN2dR0gNg0',
    appId: '1:523838006351:web:42aea1b63d1f7d3307363a',
    messagingSenderId: '523838006351',
    projectId: 'studienbuch-3aa23',
    authDomain: 'studienbuch-3aa23.firebaseapp.com',
    storageBucket: 'studienbuch-3aa23.appspot.com',
  );

}