name: "studienbuch"

services:
  database:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: stu
      POSTGRES_USER: stu
      POSTGRES_DB: stu
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "stu", "-d", "stu"]
      interval: 1s
      timeout: 5s
      retries: 60
    volumes:
      - postgres_data:/var/lib/postgresql/data

  event-stream:
    image: rabbitmq:4-management-alpine
    restart: unless-stopped
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    configs:
      - source: enabled_plugins
        target: /etc/rabbitmq/enabled_plugins
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "is_running"]
      interval: 10s
      timeout: 5s
      retries: 60

  api:
    profiles: [live]
    image: studienbuch-api:nix
    pull_policy: never
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
      event-stream:
        condition: service_started
      migrations:
        condition: service_completed_successfully
    environment:
      MANAGEMENT_DATABASE_URL: postgresql://stu:stu@database:5432/stu
      PULSAR_URL: pulsar://event-stream:6650
      API_PORT: 80
      LINEAR_API_KEY: ${LINEAR_API_KEY:?LINEAR_API_KEY is required}
      NEXT_PUBLIC_AXIOM_DATASET: ${NEXT_PUBLIC_AXIOM_DATASET:?NEXT_PUBLIC_AXIOM_DATASET is required}
      NEXT_PUBLIC_AXIOM_TOKEN: ${NEXT_PUBLIC_AXIOM_TOKEN:?NEXT_PUBLIC_AXIOM_TOKEN is required}
      CACHE_DIR: /cache
    volumes:
      - cache:/cache

  console-cron:
    profiles: [live]
    image: studienbuch-console-cron:nix
    pull_policy: never
    depends_on:
      database:
        condition: service_healthy
      event-stream:
        condition: service_started
      migrations:
        condition: service_completed_successfully
      legacy-database:
        condition: service_healthy
    init: true
    tty: true
    environment:
      API_PORT: 80
      LINEAR_API_KEY: ${LINEAR_API_KEY:?LINEAR_API_KEY is required}
      NEXT_PUBLIC_AXIOM_DATASET: ${NEXT_PUBLIC_AXIOM_DATASET:?NEXT_PUBLIC_AXIOM_DATASET is required}
      NEXT_PUBLIC_AXIOM_TOKEN: ${NEXT_PUBLIC_AXIOM_TOKEN:?NEXT_PUBLIC_AXIOM_TOKEN is required}
      PULSAR_URL: pulsar://event-stream:6650
      MANAGEMENT_DATABASE_URL: postgresql://stu:stu@database:5432/stu
      LEGACY_DATABASE_URL: postgresql://postgres:postgres@legacy-database:5432/postgres
      UNTIS_KADMOS_NAME: ${UNTIS_KADMOS_NAME:?UNTIS_KADMOS_NAME is required}
      UNTIS_KADMOS_USERNAME: ${UNTIS_KADMOS_USERNAME:?UNTIS_KADMOS_USERNAME is required}
      UNTIS_KADMOS_PASSWORD: ${UNTIS_KADMOS_PASSWORD:?UNTIS_KADMOS_PASSWORD is required}
      CACHE_DIR: /cache
    volumes:
      - cache:/cache
    restart: unless-stopped
    configs:
      - source: crontab
        target: /var/spool/cron/crontabs/root

  migrations:
    # profiles: [live]
    image: studienbuch-migrations:nix
    pull_policy: never
    environment:
      MANAGEMENT_DATABASE_URL: postgresql://stu:stu@database:5432/stu
    depends_on:
      database:
        condition: service_healthy
    restart: no

  legacy-database:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 1s
      timeout: 5s
      retries: 60
    volumes:
      - postgres_legacy_data:/var/lib/postgresql/data

configs:
  crontab:
    content: |
      */10 * * * * console pull --school=igs-lil
      @reboot console pull --school=igs-lil

  enabled_plugins:
    content: |
      [rabbitmq_stream,rabbitmq_stream_management].

volumes:
  postgres_data:
  cache:
  rabbitmq_data:
  postgres_legacy_data:
