name: "studienbuch-prod"

services:
  management-data-storage:
    extends:
      file: docker/common-services.yaml
      service: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  event-stream:
    extends:
      file: docker/common-services.yaml
      service: pulsar
    volumes:
      - pulsar_data:/pulsar/data
      - pulsar_config:/pulsar/conf

  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: api
    restart: unless-stopped
    depends_on:
      management-data-storage:
        condition: service_started
      event-stream:
        condition: service_started
    environment:
      MANAGEMENT_DATABASE_URL: postgresql://stu:stu@management-data-storage:5432/stu
      PULSAR_URL: pulsar://event-stream:6650
      ISERV_USERNAME: $ISERV_USERNAME
      ISERV_PASSWORD: $ISERV_PASSWORD
      LINEAR_API_KEY: $LINEAR_API_KEY # TODO: remove
      NEXT_PUBLIC_AXIOM_DATASET: $AXIOM_DATASET
      NEXT_PUBLIC_AXIOM_TOKEN: $AXIOM_TOKEN

  console:
    build:
      context: .
      dockerfile: Dockerfile
      target: console
    depends_on:
      management-data-storage:
        condition: service_started
      event-stream:
        condition: service_started
    environment:
      LINEAR_API_KEY: $LINEAR_API_KEY # TODO: remove
      ISERV_USERNAME: $ISERV_USERNAME
      ISERV_PASSWORD: $ISERV_PASSWORD
      NEXT_PUBLIC_AXIOM_DATASET: $AXIOM_DATASET
      NEXT_PUBLIC_AXIOM_TOKEN: $AXIOM_TOKEN
      PULSAR_URL: pulsar://event-stream:6650
      API_PORT: 3001 # TODO: remove
      MANAGEMENT_DATABASE_URL: postgresql://stu:stu@management-data-storage:5432/stu

  cron:
    build:
      context: .
      dockerfile: Dockerfile
      target: cron
    environment:
      LINEAR_API_KEY: $LINEAR_API_KEY
      ISERV_USERNAME: $ISERV_USERNAME
      ISERV_PASSWORD: $ISERV_PASSWORD
      AXIOM_DATASET: $AXIOM_DATASET
      AXIOM_TOKEN: $AXIOM_TOKEN
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    init: true
    tty: true
    configs:
      - source: crontab
        target: /var/spool/cron/crontabs/root

configs:
  crontab:
    content: |
      */10 * * * * console pull igs-lil
      @reboot console pull igs-lil

volumes:
  postgres_data:
  pulsar_data:
  pulsar_config:
