name: "studienbuch"

services:
  management-data-storage:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: stu
      POSTGRES_USER: stu
      POSTGRES_DB: stu
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "stu", "-d", "stu"]
      interval: 1s
      timeout: 5s
      retries: 60
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: api
    restart: unless-stopped
    depends_on:
      management-data-storage:
        condition: service_healthy
      event-stream:
        condition: service_started
      migrations:
        condition: service_completed_successfully
    environment:
      MANAGEMENT_DATABASE_URL: postgresql://stu:stu@management-data-storage:5432/stu
      PULSAR_URL: pulsar://event-stream:6650
      ISERV_USERNAME: $ISERV_USERNAME
      ISERV_PASSWORD: $ISERV_PASSWORD
      LINEAR_API_KEY: $LINEAR_API_KEY # TODO: remove
      NEXT_PUBLIC_AXIOM_DATASET: $AXIOM_DATASET
      NEXT_PUBLIC_AXIOM_TOKEN: $AXIOM_TOKEN
      CACHE_DIR: /cache
    volumes:
      - cache:/cache

  console-cron:
    build:
      context: .
      dockerfile: Dockerfile
      target: console-cron
    depends_on:
      management-data-storage:
        condition: service_healthy
      event-stream:
        condition: service_started
      migrations:
        condition: service_completed_successfully
    init: true
    tty: true
    environment:
      LINEAR_API_KEY: $LINEAR_API_KEY # TODO: remove
      ISERV_USERNAME: $ISERV_USERNAME
      ISERV_PASSWORD: $ISERV_PASSWORD
      NEXT_PUBLIC_AXIOM_DATASET: $AXIOM_DATASET
      NEXT_PUBLIC_AXIOM_TOKEN: $AXIOM_TOKEN
      PULSAR_URL: pulsar://event-stream:6650
      API_PORT: 3001 # TODO: remove
      MANAGEMENT_DATABASE_URL: postgresql://stu:stu@management-data-storage:5432/stu
      LEGACY_DATABASE_URL: postgresql://postgres:postgres@docker.host.internal:5433/postgres
      CACHE_DIR: /cache
    volumes:
      - cache:/cache
    restart: unless-stopped
    configs:
      - source: crontab
        target: /var/spool/cron/crontabs/root

  migrations:
    build:
      context: .
      dockerfile: Dockerfile
      target: migrations
    environment:
      MANAGEMENT_DATABASE_URL: postgresql://stu:stu@management-data-storage:5432/stu
    depends_on:
      management-data-storage:
        condition: service_healthy
    restart: no

configs:
  crontab:
    content: |
      */10 * * * * console pull igs-lil
      @reboot console pull igs-lil

volumes:
  postgres_data:
  cache: