services:
  database:
    ports:
      - 5432:5432

  legacy-database:
    ports:
      - 5433:5432

  event-stream:
    ports:
      - 5552:5552
      - 5672:5672
      - 15672:15672

  api:
    ports:
      - 3001:80
