name: "studienbuch"

services:
  management-data-storage:
    extends:
      file: docker/common-services.yaml
      service: postgres
    ports:
      - 5432:5432

  event-stream:
    extends:
      file: docker/common-services.yaml
      service: pulsar
    ports:
      - 6650:6650
      - 8080:8080

volumes:
  postgres_data:
  pulsar_data:
  pulsar_config:
