services:
  api:
    image: studienbuch-api:nix
    pull_policy: never
    build: null

  console-cron:
    image: studienbuch-console-cron:nix
    pull_policy: never
    build: null

  migrations:
    image: studienbuch-migrations:nix
    pull_policy: never
    build: null
