name: "studienbuch"

services:
  postgres:
    extends:
      file: docker/common-services.yaml
      service: postgres
    ports:
      - 5432:5432
  rabbitmq:
    extends:
      file: docker/common-services.yaml
      service: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
      - 15674:15674
  libsql:
    extends:
      file: docker/common-services.yaml
      service: libsql
    ports:
      - 8080:8080
      - 9090:9090
