// Generated by `kiln gen` from the flake's outputs. Run it again after adding or renaming outputs.
import { Flake } from "@kiln/core"

export const flake = Flake.make({
  packages: ["projectRelease", "webApplication"],
  checks: ["projectReleaseGate", "releaseClosure", "releaseInterface", "releasePackage", "releaseSmoke", "webApplication", "workspaceSource"],
  devShells: ["ci", "default"],
})
