import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // ignore_for_file: type=lint,unused_import

// GENERATED BY drift_dev, DO NOT MODIFY.
final class _S2 extends i0.VersionedSchema {
  _S2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    teachers,
    classes,
    courses,
    courseTimes,
    absences,
    semesters,
    semesterCourses,
    gradeResults,
    tasks,
    years,
    users,
  ];
  late final Shape0 teachers = Shape0(
      source: i0.VersionedTable(
        entityName: 'teachers',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_1,
          _column_2,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape1 classes = Shape1(
      source: i0.VersionedTable(
        entityName: 'classes',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_3,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape2 courses = Shape2(
      source: i0.VersionedTable(
        entityName: 'courses',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_4,
          _column_1,
          _column_5,
          _column_6,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape3 courseTimes = Shape3(
      source: i0.VersionedTable(
        entityName: 'course_times',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_7,
          _column_8,
          _column_9,
          _column_10,
          _column_11,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape4 absences = Shape4(
      source: i0.VersionedTable(
        entityName: 'absences',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_12,
          _column_13,
          _column_14,
          _column_15,
          _column_16,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape5 semesters = Shape5(
      source: i0.VersionedTable(
        entityName: 'semesters',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(id)',
        ],
        columns: [
          _column_17,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape6 semesterCourses = Shape6(
      source: i0.VersionedTable(
        entityName: 'semester_courses',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_18,
          _column_14,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape7 gradeResults = Shape7(
      source: i0.VersionedTable(
        entityName: 'grade_results',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_12,
          _column_19,
          _column_14,
          _column_20,
          _column_21,
          _column_22,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape8 tasks = Shape8(
      source: i0.VersionedTable(
        entityName: 'tasks',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_23,
          _column_24,
          _column_25,
          _column_14,
          _column_26,
          _column_27,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape9 years = Shape9(
      source: i0.VersionedTable(
        entityName: 'years',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_28,
          _column_29,
          _column_1,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape10 users = Shape10(
      source: i0.VersionedTable(
        entityName: 'users',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_30,
          _column_31,
          _column_1,
          _column_32,
          _column_33,
        ],
        attachedDatabase: database,
      ),
      alias: null);
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_0(String aliasedName) =>
    i1.GeneratedColumn<int>('id', aliasedName, false,
        hasAutoIncrement: true,
        type: i1.DriftSqlType.int,
        defaultConstraints:
            i1.GeneratedColumn.constraintIsAlways('PRIMARY KEY AUTOINCREMENT'));
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>('name', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>('title', aliasedName, true,
        type: i1.DriftSqlType.string);

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get identifierInYear =>
      columnsByName['identifier_in_year']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_3(String aliasedName) =>
    i1.GeneratedColumn<String>('identifier_in_year', aliasedName, false,
        type: i1.DriftSqlType.string);

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get courseId =>
      columnsByName['course_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get teacher =>
      columnsByName['teacher']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get parentClass =>
      columnsByName['parent_class']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_4(String aliasedName) =>
    i1.GeneratedColumn<String>('course_id', aliasedName, true,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<int> _column_5(String aliasedName) =>
    i1.GeneratedColumn<int>('teacher', aliasedName, false,
        type: i1.DriftSqlType.int,
        defaultConstraints:
            i1.GeneratedColumn.constraintIsAlways('REFERENCES teachers (id)'));
i1.GeneratedColumn<int> _column_6(String aliasedName) =>
    i1.GeneratedColumn<int>('parent_class', aliasedName, true,
        type: i1.DriftSqlType.int,
        defaultConstraints:
            i1.GeneratedColumn.constraintIsAlways('REFERENCES classes (id)'));

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get weekday =>
      columnsByName['weekday']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get start =>
      columnsByName['start']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get duration =>
      columnsByName['duration']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get course =>
      columnsByName['course']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get weeks =>
      columnsByName['weeks']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_7(String aliasedName) =>
    i1.GeneratedColumn<int>('weekday', aliasedName, false,
        type: i1.DriftSqlType.int);
i1.GeneratedColumn<int> _column_8(String aliasedName) =>
    i1.GeneratedColumn<int>('start', aliasedName, false,
        type: i1.DriftSqlType.int);
i1.GeneratedColumn<int> _column_9(String aliasedName) =>
    i1.GeneratedColumn<int>('duration', aliasedName, false,
        type: i1.DriftSqlType.int);
i1.GeneratedColumn<int> _column_10(String aliasedName) =>
    i1.GeneratedColumn<int>('course', aliasedName, true,
        type: i1.DriftSqlType.int,
        defaultConstraints:
            i1.GeneratedColumn.constraintIsAlways('REFERENCES courses (id)'));
i1.GeneratedColumn<String> _column_11(String aliasedName) =>
    i1.GeneratedColumn<String>('weeks', aliasedName, false,
        type: i1.DriftSqlType.string);

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<DateTime> get date =>
      columnsByName['date']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<String> get reason =>
      columnsByName['reason']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get course =>
      columnsByName['course']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<bool> get isExcusedByTeacher =>
      columnsByName['is_excused_by_teacher']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<bool> get isExcusedByParent =>
      columnsByName['is_excused_by_parent']! as i1.GeneratedColumn<bool>;
}

i1.GeneratedColumn<DateTime> _column_12(String aliasedName) =>
    i1.GeneratedColumn<DateTime>('date', aliasedName, false,
        type: i1.DriftSqlType.dateTime);
i1.GeneratedColumn<String> _column_13(String aliasedName) =>
    i1.GeneratedColumn<String>('reason', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<int> _column_14(String aliasedName) =>
    i1.GeneratedColumn<int>('course', aliasedName, false,
        type: i1.DriftSqlType.int,
        defaultConstraints:
            i1.GeneratedColumn.constraintIsAlways('REFERENCES courses (id)'));
i1.GeneratedColumn<bool> _column_15(String aliasedName) =>
    i1.GeneratedColumn<bool>('is_excused_by_teacher', aliasedName, false,
        type: i1.DriftSqlType.bool,
        defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
            'CHECK ("is_excused_by_teacher" IN (0, 1))'),
        defaultValue: const Constant(false));
i1.GeneratedColumn<bool> _column_16(String aliasedName) =>
    i1.GeneratedColumn<bool>('is_excused_by_parent', aliasedName, false,
        type: i1.DriftSqlType.bool,
        defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
            'CHECK ("is_excused_by_parent" IN (0, 1))'),
        defaultValue: const Constant(false));

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_17(String aliasedName) =>
    i1.GeneratedColumn<int>('id', aliasedName, false,
        type: i1.DriftSqlType.int);

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get semester =>
      columnsByName['semester']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get course =>
      columnsByName['course']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_18(String aliasedName) =>
    i1.GeneratedColumn<int>('semester', aliasedName, false,
        type: i1.DriftSqlType.int,
        defaultConstraints:
            i1.GeneratedColumn.constraintIsAlways('REFERENCES semesters (id)'));

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<DateTime> get date =>
      columnsByName['date']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<double> get result =>
      columnsByName['result']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get course =>
      columnsByName['course']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get type =>
      columnsByName['type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<bool> get isConfirmedByTeacher =>
      columnsByName['is_confirmed_by_teacher']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<bool> get isConfirmedByParent =>
      columnsByName['is_confirmed_by_parent']! as i1.GeneratedColumn<bool>;
}

i1.GeneratedColumn<double> _column_19(String aliasedName) =>
    i1.GeneratedColumn<double>('result', aliasedName, false,
        type: i1.DriftSqlType.double);
i1.GeneratedColumn<String> _column_20(String aliasedName) =>
    i1.GeneratedColumn<String>('type', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<bool> _column_21(String aliasedName) =>
    i1.GeneratedColumn<bool>('is_confirmed_by_teacher', aliasedName, false,
        type: i1.DriftSqlType.bool,
        defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
            'CHECK ("is_confirmed_by_teacher" IN (0, 1))'),
        defaultValue: const Constant(false));
i1.GeneratedColumn<bool> _column_22(String aliasedName) =>
    i1.GeneratedColumn<bool>('is_confirmed_by_parent', aliasedName, false,
        type: i1.DriftSqlType.bool,
        defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
            'CHECK ("is_confirmed_by_parent" IN (0, 1))'),
        defaultValue: const Constant(false));

class Shape8 extends i0.VersionedTable {
  Shape8({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get dueDate =>
      columnsByName['due_date']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<int> get course =>
      columnsByName['course']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get images =>
      columnsByName['images']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<bool> get done =>
      columnsByName['done']! as i1.GeneratedColumn<bool>;
}

i1.GeneratedColumn<String> _column_23(String aliasedName) =>
    i1.GeneratedColumn<String>('title', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_24(String aliasedName) =>
    i1.GeneratedColumn<String>('description', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<DateTime> _column_25(String aliasedName) =>
    i1.GeneratedColumn<DateTime>('due_date', aliasedName, false,
        type: i1.DriftSqlType.dateTime);
i1.GeneratedColumn<String> _column_26(String aliasedName) =>
    i1.GeneratedColumn<String>('images', aliasedName, false,
        type: i1.DriftSqlType.string, defaultValue: const Constant(""));
i1.GeneratedColumn<bool> _column_27(String aliasedName) =>
    i1.GeneratedColumn<bool>('done', aliasedName, false,
        type: i1.DriftSqlType.bool,
        defaultConstraints:
            i1.GeneratedColumn.constraintIsAlways('CHECK ("done" IN (0, 1))'),
        defaultValue: const Constant(false));

class Shape9 extends i0.VersionedTable {
  Shape9({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get startYear =>
      columnsByName['start_year']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get graduationYear =>
      columnsByName['graduation_year']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_28(String aliasedName) =>
    i1.GeneratedColumn<int>('start_year', aliasedName, false,
        type: i1.DriftSqlType.int);
i1.GeneratedColumn<int> _column_29(String aliasedName) =>
    i1.GeneratedColumn<int>('graduation_year', aliasedName, false,
        type: i1.DriftSqlType.int);

class Shape10 extends i0.VersionedTable {
  Shape10({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get licenseKey =>
      columnsByName['license_key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get licenseKeyActivatedAt =>
      columnsByName['license_key_activated_at']!
          as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<bool> get isOfAge =>
      columnsByName['is_of_age']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<int> get year =>
      columnsByName['year']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_30(String aliasedName) =>
    i1.GeneratedColumn<String>('license_key', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<DateTime> _column_31(String aliasedName) =>
    i1.GeneratedColumn<DateTime>('license_key_activated_at', aliasedName, false,
        type: i1.DriftSqlType.dateTime);
i1.GeneratedColumn<bool> _column_32(String aliasedName) =>
    i1.GeneratedColumn<bool>('is_of_age', aliasedName, false,
        type: i1.DriftSqlType.bool,
        defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
            'CHECK ("is_of_age" IN (0, 1))'));
i1.GeneratedColumn<int> _column_33(String aliasedName) =>
    i1.GeneratedColumn<int>('year', aliasedName, false,
        type: i1.DriftSqlType.int,
        defaultConstraints:
            i1.GeneratedColumn.constraintIsAlways('REFERENCES years (id)'));

final class _S3 extends i0.VersionedSchema {
  _S3({required super.database}) : super(version: 3);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    teachers,
    classes,
    courses,
    courseTimes,
    absences,
    semesters,
    semesterCourses,
    gradeResults,
    tasks,
    years,
    users,
  ];
  late final Shape0 teachers = Shape0(
      source: i0.VersionedTable(
        entityName: 'teachers',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_1,
          _column_2,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape1 classes = Shape1(
      source: i0.VersionedTable(
        entityName: 'classes',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_3,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape2 courses = Shape2(
      source: i0.VersionedTable(
        entityName: 'courses',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_4,
          _column_1,
          _column_5,
          _column_6,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape3 courseTimes = Shape3(
      source: i0.VersionedTable(
        entityName: 'course_times',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_7,
          _column_8,
          _column_9,
          _column_10,
          _column_11,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape4 absences = Shape4(
      source: i0.VersionedTable(
        entityName: 'absences',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_12,
          _column_13,
          _column_14,
          _column_15,
          _column_16,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape5 semesters = Shape5(
      source: i0.VersionedTable(
        entityName: 'semesters',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(id)',
        ],
        columns: [
          _column_17,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape6 semesterCourses = Shape6(
      source: i0.VersionedTable(
        entityName: 'semester_courses',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_18,
          _column_14,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape7 gradeResults = Shape7(
      source: i0.VersionedTable(
        entityName: 'grade_results',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_12,
          _column_19,
          _column_14,
          _column_20,
          _column_21,
          _column_22,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape8 tasks = Shape8(
      source: i0.VersionedTable(
        entityName: 'tasks',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_23,
          _column_24,
          _column_25,
          _column_14,
          _column_26,
          _column_27,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape9 years = Shape9(
      source: i0.VersionedTable(
        entityName: 'years',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_28,
          _column_29,
          _column_1,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape11 users = Shape11(
      source: i0.VersionedTable(
        entityName: 'users',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_30,
          _column_31,
          _column_1,
          _column_32,
          _column_33,
          _column_34,
          _column_35,
        ],
        attachedDatabase: database,
      ),
      alias: null);
}

class Shape11 extends i0.VersionedTable {
  Shape11({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get licenseKey =>
      columnsByName['license_key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get licenseKeyActivatedAt =>
      columnsByName['license_key_activated_at']!
          as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<bool> get isOfAge =>
      columnsByName['is_of_age']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<int> get year =>
      columnsByName['year']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<DateTime> get lastSyncedAt =>
      columnsByName['last_synced_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get lastFullSyncedAt =>
      columnsByName['last_full_synced_at']! as i1.GeneratedColumn<DateTime>;
}

i1.GeneratedColumn<DateTime> _column_34(String aliasedName) =>
    i1.GeneratedColumn<DateTime>('last_synced_at', aliasedName, true,
        type: i1.DriftSqlType.dateTime);
i1.GeneratedColumn<DateTime> _column_35(String aliasedName) =>
    i1.GeneratedColumn<DateTime>('last_full_synced_at', aliasedName, true,
        type: i1.DriftSqlType.dateTime);

final class _S4 extends i0.VersionedSchema {
  _S4({required super.database}) : super(version: 4);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    teachers,
    classes,
    courses,
    courseTimes,
    absences,
    semesters,
    semesterCourses,
    gradeResults,
    tasks,
    years,
    users,
  ];
  late final Shape0 teachers = Shape0(
      source: i0.VersionedTable(
        entityName: 'teachers',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_1,
          _column_2,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape1 classes = Shape1(
      source: i0.VersionedTable(
        entityName: 'classes',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_3,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape2 courses = Shape2(
      source: i0.VersionedTable(
        entityName: 'courses',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_4,
          _column_1,
          _column_5,
          _column_6,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape3 courseTimes = Shape3(
      source: i0.VersionedTable(
        entityName: 'course_times',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_7,
          _column_8,
          _column_9,
          _column_10,
          _column_11,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape4 absences = Shape4(
      source: i0.VersionedTable(
        entityName: 'absences',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_12,
          _column_13,
          _column_14,
          _column_15,
          _column_16,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape5 semesters = Shape5(
      source: i0.VersionedTable(
        entityName: 'semesters',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(id)',
        ],
        columns: [
          _column_17,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape6 semesterCourses = Shape6(
      source: i0.VersionedTable(
        entityName: 'semester_courses',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_18,
          _column_14,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape7 gradeResults = Shape7(
      source: i0.VersionedTable(
        entityName: 'grade_results',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_12,
          _column_19,
          _column_14,
          _column_20,
          _column_21,
          _column_22,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape8 tasks = Shape8(
      source: i0.VersionedTable(
        entityName: 'tasks',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_23,
          _column_24,
          _column_25,
          _column_14,
          _column_26,
          _column_27,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape9 years = Shape9(
      source: i0.VersionedTable(
        entityName: 'years',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_28,
          _column_29,
          _column_1,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape12 users = Shape12(
      source: i0.VersionedTable(
        entityName: 'users',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_30,
          _column_31,
          _column_1,
          _column_32,
          _column_33,
          _column_34,
          _column_35,
          _column_36,
        ],
        attachedDatabase: database,
      ),
      alias: null);
}

class Shape12 extends i0.VersionedTable {
  Shape12({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get licenseKey =>
      columnsByName['license_key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get licenseKeyActivatedAt =>
      columnsByName['license_key_activated_at']!
          as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<bool> get isOfAge =>
      columnsByName['is_of_age']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<int> get year =>
      columnsByName['year']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<DateTime> get lastSyncedAt =>
      columnsByName['last_synced_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get lastFullSyncedAt =>
      columnsByName['last_full_synced_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<bool> get hasCompletedScheduleTutorial =>
      columnsByName['has_completed_schedule_tutorial']!
          as i1.GeneratedColumn<bool>;
}

i1.GeneratedColumn<bool> _column_36(
        String aliasedName) =>
    i1.GeneratedColumn<bool>(
        'has_completed_schedule_tutorial', aliasedName, false,
        type: i1.DriftSqlType.bool,
        defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
            'CHECK ("has_completed_schedule_tutorial" IN (0, 1))'),
        defaultValue: const Constant(false));
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, _S2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, _S3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, _S4 schema) from3To4,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = _S2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      case 2:
        final schema = _S3(database: database);
        final migrator = i1.Migrator(database, schema);
        await from2To3(migrator, schema);
        return 3;
      case 3:
        final schema = _S4(database: database);
        final migrator = i1.Migrator(database, schema);
        await from3To4(migrator, schema);
        return 4;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, _S2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, _S3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, _S4 schema) from3To4,
}) =>
    i0.VersionedSchema.stepByStepHelper(
        step: migrationSteps(
      from1To2: from1To2,
      from2To3: from2To3,
      from3To4: from3To4,
    ));
