/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiHealthLiveRouteImport } from './routes/api/health/live'
import { Route as ApiHealthReadyRouteImport } from './routes/api/health/ready'
import { Route as ApiObservabilityV1CanaryRouteImport } from './routes/api/observability/v1/canary'
import { Route as ApiObservabilityV1TelemetryRouteImport } from './routes/api/observability/v1/telemetry'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthLiveRoute = ApiHealthLiveRouteImport.update({
  id: '/api/health/live',
  path: '/api/health/live',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthReadyRoute = ApiHealthReadyRouteImport.update({
  id: '/api/health/ready',
  path: '/api/health/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiObservabilityV1CanaryRoute =
  ApiObservabilityV1CanaryRouteImport.update({
    id: '/api/observability/v1/canary',
    path: '/api/observability/v1/canary',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiObservabilityV1TelemetryRoute =
  ApiObservabilityV1TelemetryRouteImport.update({
    id: '/api/observability/v1/telemetry',
    path: '/api/observability/v1/telemetry',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/health/live': typeof ApiHealthLiveRoute
  '/api/health/ready': typeof ApiHealthReadyRoute
  '/api/observability/v1/canary': typeof ApiObservabilityV1CanaryRoute
  '/api/observability/v1/telemetry': typeof ApiObservabilityV1TelemetryRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/health/live': typeof ApiHealthLiveRoute
  '/api/health/ready': typeof ApiHealthReadyRoute
  '/api/observability/v1/canary': typeof ApiObservabilityV1CanaryRoute
  '/api/observability/v1/telemetry': typeof ApiObservabilityV1TelemetryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/_public/': typeof PublicIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/health/live': typeof ApiHealthLiveRoute
  '/api/health/ready': typeof ApiHealthReadyRoute
  '/api/observability/v1/canary': typeof ApiObservabilityV1CanaryRoute
  '/api/observability/v1/telemetry': typeof ApiObservabilityV1TelemetryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/auth/$'
    | '/api/health/live'
    | '/api/health/ready'
    | '/api/observability/v1/canary'
    | '/api/observability/v1/telemetry'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/auth/$'
    | '/api/health/live'
    | '/api/health/ready'
    | '/api/observability/v1/canary'
    | '/api/observability/v1/telemetry'
  id:
    | '__root__'
    | '/_public'
    | '/_public/'
    | '/api/auth/$'
    | '/api/health/live'
    | '/api/health/ready'
    | '/api/observability/v1/canary'
    | '/api/observability/v1/telemetry'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiHealthLiveRoute: typeof ApiHealthLiveRoute
  ApiHealthReadyRoute: typeof ApiHealthReadyRoute
  ApiObservabilityV1CanaryRoute: typeof ApiObservabilityV1CanaryRoute
  ApiObservabilityV1TelemetryRoute: typeof ApiObservabilityV1TelemetryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health/live': {
      id: '/api/health/live'
      path: '/api/health/live'
      fullPath: '/api/health/live'
      preLoaderRoute: typeof ApiHealthLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health/ready': {
      id: '/api/health/ready'
      path: '/api/health/ready'
      fullPath: '/api/health/ready'
      preLoaderRoute: typeof ApiHealthReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/observability/v1/canary': {
      id: '/api/observability/v1/canary'
      path: '/api/observability/v1/canary'
      fullPath: '/api/observability/v1/canary'
      preLoaderRoute: typeof ApiObservabilityV1CanaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/observability/v1/telemetry': {
      id: '/api/observability/v1/telemetry'
      path: '/api/observability/v1/telemetry'
      fullPath: '/api/observability/v1/telemetry'
      preLoaderRoute: typeof ApiObservabilityV1TelemetryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PublicRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiHealthLiveRoute: ApiHealthLiveRoute,
  ApiHealthReadyRoute: ApiHealthReadyRoute,
  ApiObservabilityV1CanaryRoute: ApiObservabilityV1CanaryRoute,
  ApiObservabilityV1TelemetryRoute: ApiObservabilityV1TelemetryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
