/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ClientRouteImport } from './routes/_client'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as ClientAktivierenRouteImport } from './routes/_client.aktivieren'
import { Route as ClientAnmeldenRouteImport } from './routes/_client.anmelden'
import { Route as ClientAppRouteImport } from './routes/_client.app'
import { Route as ClientEinrichtenRouteImport } from './routes/_client.einrichten'
import { Route as ClientPasswortVergessenRouteImport } from './routes/_client.passwort-vergessen'
import { Route as ClientPasswortZuruecksetzenRouteImport } from './routes/_client.passwort-zuruecksetzen'
import { Route as ClientRegistrierenRouteImport } from './routes/_client.registrieren'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as PublicDatenschutzRouteImport } from './routes/_public.datenschutz'
import { Route as PublicImpressumRouteImport } from './routes/_public.impressum'
import { Route as ApiRpcRouteImport } from './routes/api/rpc'
import { Route as ClientAktivierenAbschliessenRouteImport } from './routes/_client.aktivieren_.abschliessen'
import { Route as ClientAppIndexRouteImport } from './routes/_client.app.index'
import { Route as ClientAppKontoRouteImport } from './routes/_client.app.konto'
import { Route as ClientAppOperatorRouteImport } from './routes/_client.app.operator'
import { Route as ClientOperatorSetupRouteImport } from './routes/_client.operator.setup'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiHealthLiveRouteImport } from './routes/api/health/live'
import { Route as ApiHealthReadyRouteImport } from './routes/api/health/ready'
import { Route as ClientAppSchoolRolleRouteImport } from './routes/_client.app.$school.$rolle'
import { Route as ClientAppOperatorIndexRouteImport } from './routes/_client.app.operator.index'
import { Route as ClientAppOperatorSchulenRouteImport } from './routes/_client.app.operator.schulen'
import { Route as ClientAppOperatorZugangscodesRouteImport } from './routes/_client.app.operator.zugangscodes'
import { Route as ApiObservabilityV1CanaryRouteImport } from './routes/api/observability/v1/canary'
import { Route as ApiObservabilityV1TelemetryRouteImport } from './routes/api/observability/v1/telemetry'
import { Route as ClientAppSchoolRolleIndexRouteImport } from './routes/_client.app.$school.$rolle.index'
import { Route as ClientAppSchoolRolleBestaetigungenRouteImport } from './routes/_client.app.$school.$rolle.bestaetigungen'
import { Route as ClientAppSchoolRolleHeuteRouteImport } from './routes/_client.app.$school.$rolle.heute'
import { Route as ClientAppSchoolRolleKurseRouteImport } from './routes/_client.app.$school.$rolle.kurse'
import { Route as ClientAppSchoolRolleWocheRouteImport } from './routes/_client.app.$school.$rolle.woche'

const ClientRoute = ClientRouteImport.update({
  id: '/_client',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientAktivierenRoute = ClientAktivierenRouteImport.update({
  id: '/aktivieren',
  path: '/aktivieren',
  getParentRoute: () => ClientRoute,
} as any)
const ClientAnmeldenRoute = ClientAnmeldenRouteImport.update({
  id: '/anmelden',
  path: '/anmelden',
  getParentRoute: () => ClientRoute,
} as any)
const ClientAppRoute = ClientAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => ClientRoute,
} as any)
const ClientEinrichtenRoute = ClientEinrichtenRouteImport.update({
  id: '/einrichten',
  path: '/einrichten',
  getParentRoute: () => ClientRoute,
} as any)
const ClientPasswortVergessenRoute = ClientPasswortVergessenRouteImport.update({
  id: '/passwort-vergessen',
  path: '/passwort-vergessen',
  getParentRoute: () => ClientRoute,
} as any)
const ClientPasswortZuruecksetzenRoute =
  ClientPasswortZuruecksetzenRouteImport.update({
    id: '/passwort-zuruecksetzen',
    path: '/passwort-zuruecksetzen',
    getParentRoute: () => ClientRoute,
  } as any)
const ClientRegistrierenRoute = ClientRegistrierenRouteImport.update({
  id: '/registrieren',
  path: '/registrieren',
  getParentRoute: () => ClientRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicDatenschutzRoute = PublicDatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => PublicRoute,
} as any)
const PublicImpressumRoute = PublicImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => PublicRoute,
} as any)
const ApiRpcRoute = ApiRpcRouteImport.update({
  id: '/api/rpc',
  path: '/api/rpc',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientAktivierenAbschliessenRoute =
  ClientAktivierenAbschliessenRouteImport.update({
    id: '/aktivieren_/abschliessen',
    path: '/aktivieren/abschliessen',
    getParentRoute: () => ClientRoute,
  } as any)
const ClientAppIndexRoute = ClientAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientAppRoute,
} as any)
const ClientAppKontoRoute = ClientAppKontoRouteImport.update({
  id: '/konto',
  path: '/konto',
  getParentRoute: () => ClientAppRoute,
} as any)
const ClientAppOperatorRoute = ClientAppOperatorRouteImport.update({
  id: '/operator',
  path: '/operator',
  getParentRoute: () => ClientAppRoute,
} as any)
const ClientOperatorSetupRoute = ClientOperatorSetupRouteImport.update({
  id: '/operator/setup',
  path: '/operator/setup',
  getParentRoute: () => ClientRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthLiveRoute = ApiHealthLiveRouteImport.update({
  id: '/api/health/live',
  path: '/api/health/live',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthReadyRoute = ApiHealthReadyRouteImport.update({
  id: '/api/health/ready',
  path: '/api/health/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientAppSchoolRolleRoute = ClientAppSchoolRolleRouteImport.update({
  id: '/$school/$rolle',
  path: '/$school/$rolle',
  getParentRoute: () => ClientAppRoute,
} as any)
const ClientAppOperatorIndexRoute = ClientAppOperatorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientAppOperatorRoute,
} as any)
const ClientAppOperatorSchulenRoute =
  ClientAppOperatorSchulenRouteImport.update({
    id: '/schulen',
    path: '/schulen',
    getParentRoute: () => ClientAppOperatorRoute,
  } as any)
const ClientAppOperatorZugangscodesRoute =
  ClientAppOperatorZugangscodesRouteImport.update({
    id: '/zugangscodes',
    path: '/zugangscodes',
    getParentRoute: () => ClientAppOperatorRoute,
  } as any)
const ApiObservabilityV1CanaryRoute =
  ApiObservabilityV1CanaryRouteImport.update({
    id: '/api/observability/v1/canary',
    path: '/api/observability/v1/canary',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiObservabilityV1TelemetryRoute =
  ApiObservabilityV1TelemetryRouteImport.update({
    id: '/api/observability/v1/telemetry',
    path: '/api/observability/v1/telemetry',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClientAppSchoolRolleIndexRoute =
  ClientAppSchoolRolleIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ClientAppSchoolRolleRoute,
  } as any)
const ClientAppSchoolRolleBestaetigungenRoute =
  ClientAppSchoolRolleBestaetigungenRouteImport.update({
    id: '/bestaetigungen',
    path: '/bestaetigungen',
    getParentRoute: () => ClientAppSchoolRolleRoute,
  } as any)
const ClientAppSchoolRolleHeuteRoute =
  ClientAppSchoolRolleHeuteRouteImport.update({
    id: '/heute',
    path: '/heute',
    getParentRoute: () => ClientAppSchoolRolleRoute,
  } as any)
const ClientAppSchoolRolleKurseRoute =
  ClientAppSchoolRolleKurseRouteImport.update({
    id: '/kurse',
    path: '/kurse',
    getParentRoute: () => ClientAppSchoolRolleRoute,
  } as any)
const ClientAppSchoolRolleWocheRoute =
  ClientAppSchoolRolleWocheRouteImport.update({
    id: '/woche',
    path: '/woche',
    getParentRoute: () => ClientAppSchoolRolleRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/aktivieren': typeof ClientAktivierenRoute
  '/anmelden': typeof ClientAnmeldenRoute
  '/app': typeof ClientAppRouteWithChildren
  '/einrichten': typeof ClientEinrichtenRoute
  '/passwort-vergessen': typeof ClientPasswortVergessenRoute
  '/passwort-zuruecksetzen': typeof ClientPasswortZuruecksetzenRoute
  '/registrieren': typeof ClientRegistrierenRoute
  '/datenschutz': typeof PublicDatenschutzRoute
  '/impressum': typeof PublicImpressumRoute
  '/api/rpc': typeof ApiRpcRoute
  '/aktivieren/abschliessen': typeof ClientAktivierenAbschliessenRoute
  '/app/konto': typeof ClientAppKontoRoute
  '/app/operator': typeof ClientAppOperatorRouteWithChildren
  '/operator/setup': typeof ClientOperatorSetupRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/health/live': typeof ApiHealthLiveRoute
  '/api/health/ready': typeof ApiHealthReadyRoute
  '/app/': typeof ClientAppIndexRoute
  '/app/$school/$rolle': typeof ClientAppSchoolRolleRouteWithChildren
  '/app/operator/schulen': typeof ClientAppOperatorSchulenRoute
  '/app/operator/zugangscodes': typeof ClientAppOperatorZugangscodesRoute
  '/api/observability/v1/canary': typeof ApiObservabilityV1CanaryRoute
  '/api/observability/v1/telemetry': typeof ApiObservabilityV1TelemetryRoute
  '/app/operator/': typeof ClientAppOperatorIndexRoute
  '/app/$school/$rolle/bestaetigungen': typeof ClientAppSchoolRolleBestaetigungenRoute
  '/app/$school/$rolle/heute': typeof ClientAppSchoolRolleHeuteRoute
  '/app/$school/$rolle/kurse': typeof ClientAppSchoolRolleKurseRoute
  '/app/$school/$rolle/woche': typeof ClientAppSchoolRolleWocheRoute
  '/app/$school/$rolle/': typeof ClientAppSchoolRolleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/aktivieren': typeof ClientAktivierenRoute
  '/anmelden': typeof ClientAnmeldenRoute
  '/einrichten': typeof ClientEinrichtenRoute
  '/passwort-vergessen': typeof ClientPasswortVergessenRoute
  '/passwort-zuruecksetzen': typeof ClientPasswortZuruecksetzenRoute
  '/registrieren': typeof ClientRegistrierenRoute
  '/datenschutz': typeof PublicDatenschutzRoute
  '/impressum': typeof PublicImpressumRoute
  '/api/rpc': typeof ApiRpcRoute
  '/aktivieren/abschliessen': typeof ClientAktivierenAbschliessenRoute
  '/app/konto': typeof ClientAppKontoRoute
  '/operator/setup': typeof ClientOperatorSetupRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/health/live': typeof ApiHealthLiveRoute
  '/api/health/ready': typeof ApiHealthReadyRoute
  '/app': typeof ClientAppIndexRoute
  '/app/operator/schulen': typeof ClientAppOperatorSchulenRoute
  '/app/operator/zugangscodes': typeof ClientAppOperatorZugangscodesRoute
  '/api/observability/v1/canary': typeof ApiObservabilityV1CanaryRoute
  '/api/observability/v1/telemetry': typeof ApiObservabilityV1TelemetryRoute
  '/app/operator': typeof ClientAppOperatorIndexRoute
  '/app/$school/$rolle/bestaetigungen': typeof ClientAppSchoolRolleBestaetigungenRoute
  '/app/$school/$rolle/heute': typeof ClientAppSchoolRolleHeuteRoute
  '/app/$school/$rolle/kurse': typeof ClientAppSchoolRolleKurseRoute
  '/app/$school/$rolle/woche': typeof ClientAppSchoolRolleWocheRoute
  '/app/$school/$rolle': typeof ClientAppSchoolRolleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_client': typeof ClientRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_client/aktivieren': typeof ClientAktivierenRoute
  '/_client/anmelden': typeof ClientAnmeldenRoute
  '/_client/app': typeof ClientAppRouteWithChildren
  '/_client/einrichten': typeof ClientEinrichtenRoute
  '/_client/passwort-vergessen': typeof ClientPasswortVergessenRoute
  '/_client/passwort-zuruecksetzen': typeof ClientPasswortZuruecksetzenRoute
  '/_client/registrieren': typeof ClientRegistrierenRoute
  '/_public/datenschutz': typeof PublicDatenschutzRoute
  '/_public/impressum': typeof PublicImpressumRoute
  '/api/rpc': typeof ApiRpcRoute
  '/_public/': typeof PublicIndexRoute
  '/_client/aktivieren_/abschliessen': typeof ClientAktivierenAbschliessenRoute
  '/_client/app/konto': typeof ClientAppKontoRoute
  '/_client/app/operator': typeof ClientAppOperatorRouteWithChildren
  '/_client/operator/setup': typeof ClientOperatorSetupRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/health/live': typeof ApiHealthLiveRoute
  '/api/health/ready': typeof ApiHealthReadyRoute
  '/_client/app/': typeof ClientAppIndexRoute
  '/_client/app/$school/$rolle': typeof ClientAppSchoolRolleRouteWithChildren
  '/_client/app/operator/schulen': typeof ClientAppOperatorSchulenRoute
  '/_client/app/operator/zugangscodes': typeof ClientAppOperatorZugangscodesRoute
  '/api/observability/v1/canary': typeof ApiObservabilityV1CanaryRoute
  '/api/observability/v1/telemetry': typeof ApiObservabilityV1TelemetryRoute
  '/_client/app/operator/': typeof ClientAppOperatorIndexRoute
  '/_client/app/$school/$rolle/bestaetigungen': typeof ClientAppSchoolRolleBestaetigungenRoute
  '/_client/app/$school/$rolle/heute': typeof ClientAppSchoolRolleHeuteRoute
  '/_client/app/$school/$rolle/kurse': typeof ClientAppSchoolRolleKurseRoute
  '/_client/app/$school/$rolle/woche': typeof ClientAppSchoolRolleWocheRoute
  '/_client/app/$school/$rolle/': typeof ClientAppSchoolRolleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aktivieren'
    | '/anmelden'
    | '/app'
    | '/einrichten'
    | '/passwort-vergessen'
    | '/passwort-zuruecksetzen'
    | '/registrieren'
    | '/datenschutz'
    | '/impressum'
    | '/api/rpc'
    | '/aktivieren/abschliessen'
    | '/app/konto'
    | '/app/operator'
    | '/operator/setup'
    | '/api/auth/$'
    | '/api/health/live'
    | '/api/health/ready'
    | '/app/'
    | '/app/$school/$rolle'
    | '/app/operator/schulen'
    | '/app/operator/zugangscodes'
    | '/api/observability/v1/canary'
    | '/api/observability/v1/telemetry'
    | '/app/operator/'
    | '/app/$school/$rolle/bestaetigungen'
    | '/app/$school/$rolle/heute'
    | '/app/$school/$rolle/kurse'
    | '/app/$school/$rolle/woche'
    | '/app/$school/$rolle/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aktivieren'
    | '/anmelden'
    | '/einrichten'
    | '/passwort-vergessen'
    | '/passwort-zuruecksetzen'
    | '/registrieren'
    | '/datenschutz'
    | '/impressum'
    | '/api/rpc'
    | '/aktivieren/abschliessen'
    | '/app/konto'
    | '/operator/setup'
    | '/api/auth/$'
    | '/api/health/live'
    | '/api/health/ready'
    | '/app'
    | '/app/operator/schulen'
    | '/app/operator/zugangscodes'
    | '/api/observability/v1/canary'
    | '/api/observability/v1/telemetry'
    | '/app/operator'
    | '/app/$school/$rolle/bestaetigungen'
    | '/app/$school/$rolle/heute'
    | '/app/$school/$rolle/kurse'
    | '/app/$school/$rolle/woche'
    | '/app/$school/$rolle'
  id:
    | '__root__'
    | '/_client'
    | '/_public'
    | '/_client/aktivieren'
    | '/_client/anmelden'
    | '/_client/app'
    | '/_client/einrichten'
    | '/_client/passwort-vergessen'
    | '/_client/passwort-zuruecksetzen'
    | '/_client/registrieren'
    | '/_public/datenschutz'
    | '/_public/impressum'
    | '/api/rpc'
    | '/_public/'
    | '/_client/aktivieren_/abschliessen'
    | '/_client/app/konto'
    | '/_client/app/operator'
    | '/_client/operator/setup'
    | '/api/auth/$'
    | '/api/health/live'
    | '/api/health/ready'
    | '/_client/app/'
    | '/_client/app/$school/$rolle'
    | '/_client/app/operator/schulen'
    | '/_client/app/operator/zugangscodes'
    | '/api/observability/v1/canary'
    | '/api/observability/v1/telemetry'
    | '/_client/app/operator/'
    | '/_client/app/$school/$rolle/bestaetigungen'
    | '/_client/app/$school/$rolle/heute'
    | '/_client/app/$school/$rolle/kurse'
    | '/_client/app/$school/$rolle/woche'
    | '/_client/app/$school/$rolle/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ClientRoute: typeof ClientRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  ApiRpcRoute: typeof ApiRpcRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiHealthLiveRoute: typeof ApiHealthLiveRoute
  ApiHealthReadyRoute: typeof ApiHealthReadyRoute
  ApiObservabilityV1CanaryRoute: typeof ApiObservabilityV1CanaryRoute
  ApiObservabilityV1TelemetryRoute: typeof ApiObservabilityV1TelemetryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_client': {
      id: '/_client'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_client/aktivieren': {
      id: '/_client/aktivieren'
      path: '/aktivieren'
      fullPath: '/aktivieren'
      preLoaderRoute: typeof ClientAktivierenRouteImport
      parentRoute: typeof ClientRoute
    }
    '/_client/anmelden': {
      id: '/_client/anmelden'
      path: '/anmelden'
      fullPath: '/anmelden'
      preLoaderRoute: typeof ClientAnmeldenRouteImport
      parentRoute: typeof ClientRoute
    }
    '/_client/app': {
      id: '/_client/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof ClientAppRouteImport
      parentRoute: typeof ClientRoute
    }
    '/_client/einrichten': {
      id: '/_client/einrichten'
      path: '/einrichten'
      fullPath: '/einrichten'
      preLoaderRoute: typeof ClientEinrichtenRouteImport
      parentRoute: typeof ClientRoute
    }
    '/_client/passwort-vergessen': {
      id: '/_client/passwort-vergessen'
      path: '/passwort-vergessen'
      fullPath: '/passwort-vergessen'
      preLoaderRoute: typeof ClientPasswortVergessenRouteImport
      parentRoute: typeof ClientRoute
    }
    '/_client/passwort-zuruecksetzen': {
      id: '/_client/passwort-zuruecksetzen'
      path: '/passwort-zuruecksetzen'
      fullPath: '/passwort-zuruecksetzen'
      preLoaderRoute: typeof ClientPasswortZuruecksetzenRouteImport
      parentRoute: typeof ClientRoute
    }
    '/_client/registrieren': {
      id: '/_client/registrieren'
      path: '/registrieren'
      fullPath: '/registrieren'
      preLoaderRoute: typeof ClientRegistrierenRouteImport
      parentRoute: typeof ClientRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/datenschutz': {
      id: '/_public/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof PublicDatenschutzRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/impressum': {
      id: '/_public/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof PublicImpressumRouteImport
      parentRoute: typeof PublicRoute
    }
    '/api/rpc': {
      id: '/api/rpc'
      path: '/api/rpc'
      fullPath: '/api/rpc'
      preLoaderRoute: typeof ApiRpcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_client/aktivieren_/abschliessen': {
      id: '/_client/aktivieren_/abschliessen'
      path: '/aktivieren/abschliessen'
      fullPath: '/aktivieren/abschliessen'
      preLoaderRoute: typeof ClientAktivierenAbschliessenRouteImport
      parentRoute: typeof ClientRoute
    }
    '/_client/app/': {
      id: '/_client/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof ClientAppIndexRouteImport
      parentRoute: typeof ClientAppRoute
    }
    '/_client/app/konto': {
      id: '/_client/app/konto'
      path: '/konto'
      fullPath: '/app/konto'
      preLoaderRoute: typeof ClientAppKontoRouteImport
      parentRoute: typeof ClientAppRoute
    }
    '/_client/app/operator': {
      id: '/_client/app/operator'
      path: '/operator'
      fullPath: '/app/operator'
      preLoaderRoute: typeof ClientAppOperatorRouteImport
      parentRoute: typeof ClientAppRoute
    }
    '/_client/operator/setup': {
      id: '/_client/operator/setup'
      path: '/operator/setup'
      fullPath: '/operator/setup'
      preLoaderRoute: typeof ClientOperatorSetupRouteImport
      parentRoute: typeof ClientRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health/live': {
      id: '/api/health/live'
      path: '/api/health/live'
      fullPath: '/api/health/live'
      preLoaderRoute: typeof ApiHealthLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health/ready': {
      id: '/api/health/ready'
      path: '/api/health/ready'
      fullPath: '/api/health/ready'
      preLoaderRoute: typeof ApiHealthReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_client/app/$school/$rolle': {
      id: '/_client/app/$school/$rolle'
      path: '/$school/$rolle'
      fullPath: '/app/$school/$rolle'
      preLoaderRoute: typeof ClientAppSchoolRolleRouteImport
      parentRoute: typeof ClientAppRoute
    }
    '/_client/app/operator/': {
      id: '/_client/app/operator/'
      path: '/'
      fullPath: '/app/operator/'
      preLoaderRoute: typeof ClientAppOperatorIndexRouteImport
      parentRoute: typeof ClientAppOperatorRoute
    }
    '/_client/app/operator/schulen': {
      id: '/_client/app/operator/schulen'
      path: '/schulen'
      fullPath: '/app/operator/schulen'
      preLoaderRoute: typeof ClientAppOperatorSchulenRouteImport
      parentRoute: typeof ClientAppOperatorRoute
    }
    '/_client/app/operator/zugangscodes': {
      id: '/_client/app/operator/zugangscodes'
      path: '/zugangscodes'
      fullPath: '/app/operator/zugangscodes'
      preLoaderRoute: typeof ClientAppOperatorZugangscodesRouteImport
      parentRoute: typeof ClientAppOperatorRoute
    }
    '/api/observability/v1/canary': {
      id: '/api/observability/v1/canary'
      path: '/api/observability/v1/canary'
      fullPath: '/api/observability/v1/canary'
      preLoaderRoute: typeof ApiObservabilityV1CanaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/observability/v1/telemetry': {
      id: '/api/observability/v1/telemetry'
      path: '/api/observability/v1/telemetry'
      fullPath: '/api/observability/v1/telemetry'
      preLoaderRoute: typeof ApiObservabilityV1TelemetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_client/app/$school/$rolle/': {
      id: '/_client/app/$school/$rolle/'
      path: '/'
      fullPath: '/app/$school/$rolle/'
      preLoaderRoute: typeof ClientAppSchoolRolleIndexRouteImport
      parentRoute: typeof ClientAppSchoolRolleRoute
    }
    '/_client/app/$school/$rolle/bestaetigungen': {
      id: '/_client/app/$school/$rolle/bestaetigungen'
      path: '/bestaetigungen'
      fullPath: '/app/$school/$rolle/bestaetigungen'
      preLoaderRoute: typeof ClientAppSchoolRolleBestaetigungenRouteImport
      parentRoute: typeof ClientAppSchoolRolleRoute
    }
    '/_client/app/$school/$rolle/heute': {
      id: '/_client/app/$school/$rolle/heute'
      path: '/heute'
      fullPath: '/app/$school/$rolle/heute'
      preLoaderRoute: typeof ClientAppSchoolRolleHeuteRouteImport
      parentRoute: typeof ClientAppSchoolRolleRoute
    }
    '/_client/app/$school/$rolle/kurse': {
      id: '/_client/app/$school/$rolle/kurse'
      path: '/kurse'
      fullPath: '/app/$school/$rolle/kurse'
      preLoaderRoute: typeof ClientAppSchoolRolleKurseRouteImport
      parentRoute: typeof ClientAppSchoolRolleRoute
    }
    '/_client/app/$school/$rolle/woche': {
      id: '/_client/app/$school/$rolle/woche'
      path: '/woche'
      fullPath: '/app/$school/$rolle/woche'
      preLoaderRoute: typeof ClientAppSchoolRolleWocheRouteImport
      parentRoute: typeof ClientAppSchoolRolleRoute
    }
  }
}

interface ClientAppOperatorRouteChildren {
  ClientAppOperatorSchulenRoute: typeof ClientAppOperatorSchulenRoute
  ClientAppOperatorZugangscodesRoute: typeof ClientAppOperatorZugangscodesRoute
  ClientAppOperatorIndexRoute: typeof ClientAppOperatorIndexRoute
}

const ClientAppOperatorRouteChildren: ClientAppOperatorRouteChildren = {
  ClientAppOperatorSchulenRoute: ClientAppOperatorSchulenRoute,
  ClientAppOperatorZugangscodesRoute: ClientAppOperatorZugangscodesRoute,
  ClientAppOperatorIndexRoute: ClientAppOperatorIndexRoute,
}

const ClientAppOperatorRouteWithChildren =
  ClientAppOperatorRoute._addFileChildren(ClientAppOperatorRouteChildren)

interface ClientAppSchoolRolleRouteChildren {
  ClientAppSchoolRolleBestaetigungenRoute: typeof ClientAppSchoolRolleBestaetigungenRoute
  ClientAppSchoolRolleHeuteRoute: typeof ClientAppSchoolRolleHeuteRoute
  ClientAppSchoolRolleKurseRoute: typeof ClientAppSchoolRolleKurseRoute
  ClientAppSchoolRolleWocheRoute: typeof ClientAppSchoolRolleWocheRoute
  ClientAppSchoolRolleIndexRoute: typeof ClientAppSchoolRolleIndexRoute
}

const ClientAppSchoolRolleRouteChildren: ClientAppSchoolRolleRouteChildren = {
  ClientAppSchoolRolleBestaetigungenRoute:
    ClientAppSchoolRolleBestaetigungenRoute,
  ClientAppSchoolRolleHeuteRoute: ClientAppSchoolRolleHeuteRoute,
  ClientAppSchoolRolleKurseRoute: ClientAppSchoolRolleKurseRoute,
  ClientAppSchoolRolleWocheRoute: ClientAppSchoolRolleWocheRoute,
  ClientAppSchoolRolleIndexRoute: ClientAppSchoolRolleIndexRoute,
}

const ClientAppSchoolRolleRouteWithChildren =
  ClientAppSchoolRolleRoute._addFileChildren(ClientAppSchoolRolleRouteChildren)

interface ClientAppRouteChildren {
  ClientAppKontoRoute: typeof ClientAppKontoRoute
  ClientAppOperatorRoute: typeof ClientAppOperatorRouteWithChildren
  ClientAppIndexRoute: typeof ClientAppIndexRoute
  ClientAppSchoolRolleRoute: typeof ClientAppSchoolRolleRouteWithChildren
}

const ClientAppRouteChildren: ClientAppRouteChildren = {
  ClientAppKontoRoute: ClientAppKontoRoute,
  ClientAppOperatorRoute: ClientAppOperatorRouteWithChildren,
  ClientAppIndexRoute: ClientAppIndexRoute,
  ClientAppSchoolRolleRoute: ClientAppSchoolRolleRouteWithChildren,
}

const ClientAppRouteWithChildren = ClientAppRoute._addFileChildren(
  ClientAppRouteChildren,
)

interface ClientRouteChildren {
  ClientAktivierenRoute: typeof ClientAktivierenRoute
  ClientAnmeldenRoute: typeof ClientAnmeldenRoute
  ClientAppRoute: typeof ClientAppRouteWithChildren
  ClientEinrichtenRoute: typeof ClientEinrichtenRoute
  ClientPasswortVergessenRoute: typeof ClientPasswortVergessenRoute
  ClientPasswortZuruecksetzenRoute: typeof ClientPasswortZuruecksetzenRoute
  ClientRegistrierenRoute: typeof ClientRegistrierenRoute
  ClientAktivierenAbschliessenRoute: typeof ClientAktivierenAbschliessenRoute
  ClientOperatorSetupRoute: typeof ClientOperatorSetupRoute
}

const ClientRouteChildren: ClientRouteChildren = {
  ClientAktivierenRoute: ClientAktivierenRoute,
  ClientAnmeldenRoute: ClientAnmeldenRoute,
  ClientAppRoute: ClientAppRouteWithChildren,
  ClientEinrichtenRoute: ClientEinrichtenRoute,
  ClientPasswortVergessenRoute: ClientPasswortVergessenRoute,
  ClientPasswortZuruecksetzenRoute: ClientPasswortZuruecksetzenRoute,
  ClientRegistrierenRoute: ClientRegistrierenRoute,
  ClientAktivierenAbschliessenRoute: ClientAktivierenAbschliessenRoute,
  ClientOperatorSetupRoute: ClientOperatorSetupRoute,
}

const ClientRouteWithChildren =
  ClientRoute._addFileChildren(ClientRouteChildren)

interface PublicRouteChildren {
  PublicDatenschutzRoute: typeof PublicDatenschutzRoute
  PublicImpressumRoute: typeof PublicImpressumRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicDatenschutzRoute: PublicDatenschutzRoute,
  PublicImpressumRoute: PublicImpressumRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ClientRoute: ClientRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  ApiRpcRoute: ApiRpcRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiHealthLiveRoute: ApiHealthLiveRoute,
  ApiHealthReadyRoute: ApiHealthReadyRoute,
  ApiObservabilityV1CanaryRoute: ApiObservabilityV1CanaryRoute,
  ApiObservabilityV1TelemetryRoute: ApiObservabilityV1TelemetryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
