/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AktivierenRouteImport } from './routes/aktivieren'
import { Route as AnmeldenRouteImport } from './routes/anmelden'
import { Route as AppRouteImport } from './routes/app'
import { Route as EinrichtenRouteImport } from './routes/einrichten'
import { Route as PasswortVergessenRouteImport } from './routes/passwort-vergessen'
import { Route as PasswortZuruecksetzenRouteImport } from './routes/passwort-zuruecksetzen'
import { Route as RegistrierenRouteImport } from './routes/registrieren'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as PublicDatenschutzRouteImport } from './routes/_public.datenschutz'
import { Route as PublicImpressumRouteImport } from './routes/_public.impressum'
import { Route as AktivierenAbschliessenRouteImport } from './routes/aktivieren_.abschliessen'
import { Route as ApiRpcRouteImport } from './routes/api/rpc'
import { Route as OperatorSetupRouteImport } from './routes/operator/setup'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiHealthLiveRouteImport } from './routes/api/health/live'
import { Route as ApiHealthReadyRouteImport } from './routes/api/health/ready'
import { Route as ApiObservabilityV1CanaryRouteImport } from './routes/api/observability/v1/canary'
import { Route as ApiObservabilityV1TelemetryRouteImport } from './routes/api/observability/v1/telemetry'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AktivierenRoute = AktivierenRouteImport.update({
  id: '/aktivieren',
  path: '/aktivieren',
  getParentRoute: () => rootRouteImport,
} as any)
const AnmeldenRoute = AnmeldenRouteImport.update({
  id: '/anmelden',
  path: '/anmelden',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const EinrichtenRoute = EinrichtenRouteImport.update({
  id: '/einrichten',
  path: '/einrichten',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswortVergessenRoute = PasswortVergessenRouteImport.update({
  id: '/passwort-vergessen',
  path: '/passwort-vergessen',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswortZuruecksetzenRoute = PasswortZuruecksetzenRouteImport.update({
  id: '/passwort-zuruecksetzen',
  path: '/passwort-zuruecksetzen',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrierenRoute = RegistrierenRouteImport.update({
  id: '/registrieren',
  path: '/registrieren',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicDatenschutzRoute = PublicDatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => PublicRoute,
} as any)
const PublicImpressumRoute = PublicImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => PublicRoute,
} as any)
const AktivierenAbschliessenRoute = AktivierenAbschliessenRouteImport.update({
  id: '/aktivieren_/abschliessen',
  path: '/aktivieren/abschliessen',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcRoute = ApiRpcRouteImport.update({
  id: '/api/rpc',
  path: '/api/rpc',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorSetupRoute = OperatorSetupRouteImport.update({
  id: '/operator/setup',
  path: '/operator/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthLiveRoute = ApiHealthLiveRouteImport.update({
  id: '/api/health/live',
  path: '/api/health/live',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthReadyRoute = ApiHealthReadyRouteImport.update({
  id: '/api/health/ready',
  path: '/api/health/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiObservabilityV1CanaryRoute =
  ApiObservabilityV1CanaryRouteImport.update({
    id: '/api/observability/v1/canary',
    path: '/api/observability/v1/canary',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiObservabilityV1TelemetryRoute =
  ApiObservabilityV1TelemetryRouteImport.update({
    id: '/api/observability/v1/telemetry',
    path: '/api/observability/v1/telemetry',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/aktivieren': typeof AktivierenRoute
  '/anmelden': typeof AnmeldenRoute
  '/app': typeof AppRoute
  '/einrichten': typeof EinrichtenRoute
  '/passwort-vergessen': typeof PasswortVergessenRoute
  '/passwort-zuruecksetzen': typeof PasswortZuruecksetzenRoute
  '/registrieren': typeof RegistrierenRoute
  '/datenschutz': typeof PublicDatenschutzRoute
  '/impressum': typeof PublicImpressumRoute
  '/aktivieren/abschliessen': typeof AktivierenAbschliessenRoute
  '/api/rpc': typeof ApiRpcRoute
  '/operator/setup': typeof OperatorSetupRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/health/live': typeof ApiHealthLiveRoute
  '/api/health/ready': typeof ApiHealthReadyRoute
  '/api/observability/v1/canary': typeof ApiObservabilityV1CanaryRoute
  '/api/observability/v1/telemetry': typeof ApiObservabilityV1TelemetryRoute
}
export interface FileRoutesByTo {
  '/aktivieren': typeof AktivierenRoute
  '/anmelden': typeof AnmeldenRoute
  '/app': typeof AppRoute
  '/einrichten': typeof EinrichtenRoute
  '/passwort-vergessen': typeof PasswortVergessenRoute
  '/passwort-zuruecksetzen': typeof PasswortZuruecksetzenRoute
  '/registrieren': typeof RegistrierenRoute
  '/datenschutz': typeof PublicDatenschutzRoute
  '/impressum': typeof PublicImpressumRoute
  '/aktivieren/abschliessen': typeof AktivierenAbschliessenRoute
  '/api/rpc': typeof ApiRpcRoute
  '/operator/setup': typeof OperatorSetupRoute
  '/': typeof PublicIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/health/live': typeof ApiHealthLiveRoute
  '/api/health/ready': typeof ApiHealthReadyRoute
  '/api/observability/v1/canary': typeof ApiObservabilityV1CanaryRoute
  '/api/observability/v1/telemetry': typeof ApiObservabilityV1TelemetryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/aktivieren': typeof AktivierenRoute
  '/anmelden': typeof AnmeldenRoute
  '/app': typeof AppRoute
  '/einrichten': typeof EinrichtenRoute
  '/passwort-vergessen': typeof PasswortVergessenRoute
  '/passwort-zuruecksetzen': typeof PasswortZuruecksetzenRoute
  '/registrieren': typeof RegistrierenRoute
  '/_public/datenschutz': typeof PublicDatenschutzRoute
  '/_public/impressum': typeof PublicImpressumRoute
  '/aktivieren_/abschliessen': typeof AktivierenAbschliessenRoute
  '/api/rpc': typeof ApiRpcRoute
  '/operator/setup': typeof OperatorSetupRoute
  '/_public/': typeof PublicIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/health/live': typeof ApiHealthLiveRoute
  '/api/health/ready': typeof ApiHealthReadyRoute
  '/api/observability/v1/canary': typeof ApiObservabilityV1CanaryRoute
  '/api/observability/v1/telemetry': typeof ApiObservabilityV1TelemetryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aktivieren'
    | '/anmelden'
    | '/app'
    | '/einrichten'
    | '/passwort-vergessen'
    | '/passwort-zuruecksetzen'
    | '/registrieren'
    | '/datenschutz'
    | '/impressum'
    | '/aktivieren/abschliessen'
    | '/api/rpc'
    | '/operator/setup'
    | '/api/auth/$'
    | '/api/health/live'
    | '/api/health/ready'
    | '/api/observability/v1/canary'
    | '/api/observability/v1/telemetry'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/aktivieren'
    | '/anmelden'
    | '/app'
    | '/einrichten'
    | '/passwort-vergessen'
    | '/passwort-zuruecksetzen'
    | '/registrieren'
    | '/datenschutz'
    | '/impressum'
    | '/aktivieren/abschliessen'
    | '/api/rpc'
    | '/operator/setup'
    | '/'
    | '/api/auth/$'
    | '/api/health/live'
    | '/api/health/ready'
    | '/api/observability/v1/canary'
    | '/api/observability/v1/telemetry'
  id:
    | '__root__'
    | '/_public'
    | '/aktivieren'
    | '/anmelden'
    | '/app'
    | '/einrichten'
    | '/passwort-vergessen'
    | '/passwort-zuruecksetzen'
    | '/registrieren'
    | '/_public/datenschutz'
    | '/_public/impressum'
    | '/aktivieren_/abschliessen'
    | '/api/rpc'
    | '/operator/setup'
    | '/_public/'
    | '/api/auth/$'
    | '/api/health/live'
    | '/api/health/ready'
    | '/api/observability/v1/canary'
    | '/api/observability/v1/telemetry'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  AktivierenRoute: typeof AktivierenRoute
  AnmeldenRoute: typeof AnmeldenRoute
  AppRoute: typeof AppRoute
  EinrichtenRoute: typeof EinrichtenRoute
  PasswortVergessenRoute: typeof PasswortVergessenRoute
  PasswortZuruecksetzenRoute: typeof PasswortZuruecksetzenRoute
  RegistrierenRoute: typeof RegistrierenRoute
  AktivierenAbschliessenRoute: typeof AktivierenAbschliessenRoute
  ApiRpcRoute: typeof ApiRpcRoute
  OperatorSetupRoute: typeof OperatorSetupRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiHealthLiveRoute: typeof ApiHealthLiveRoute
  ApiHealthReadyRoute: typeof ApiHealthReadyRoute
  ApiObservabilityV1CanaryRoute: typeof ApiObservabilityV1CanaryRoute
  ApiObservabilityV1TelemetryRoute: typeof ApiObservabilityV1TelemetryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aktivieren': {
      id: '/aktivieren'
      path: '/aktivieren'
      fullPath: '/aktivieren'
      preLoaderRoute: typeof AktivierenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anmelden': {
      id: '/anmelden'
      path: '/anmelden'
      fullPath: '/anmelden'
      preLoaderRoute: typeof AnmeldenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/einrichten': {
      id: '/einrichten'
      path: '/einrichten'
      fullPath: '/einrichten'
      preLoaderRoute: typeof EinrichtenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passwort-vergessen': {
      id: '/passwort-vergessen'
      path: '/passwort-vergessen'
      fullPath: '/passwort-vergessen'
      preLoaderRoute: typeof PasswortVergessenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passwort-zuruecksetzen': {
      id: '/passwort-zuruecksetzen'
      path: '/passwort-zuruecksetzen'
      fullPath: '/passwort-zuruecksetzen'
      preLoaderRoute: typeof PasswortZuruecksetzenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registrieren': {
      id: '/registrieren'
      path: '/registrieren'
      fullPath: '/registrieren'
      preLoaderRoute: typeof RegistrierenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/datenschutz': {
      id: '/_public/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof PublicDatenschutzRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/impressum': {
      id: '/_public/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof PublicImpressumRouteImport
      parentRoute: typeof PublicRoute
    }
    '/aktivieren_/abschliessen': {
      id: '/aktivieren_/abschliessen'
      path: '/aktivieren/abschliessen'
      fullPath: '/aktivieren/abschliessen'
      preLoaderRoute: typeof AktivierenAbschliessenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc': {
      id: '/api/rpc'
      path: '/api/rpc'
      fullPath: '/api/rpc'
      preLoaderRoute: typeof ApiRpcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator/setup': {
      id: '/operator/setup'
      path: '/operator/setup'
      fullPath: '/operator/setup'
      preLoaderRoute: typeof OperatorSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health/live': {
      id: '/api/health/live'
      path: '/api/health/live'
      fullPath: '/api/health/live'
      preLoaderRoute: typeof ApiHealthLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health/ready': {
      id: '/api/health/ready'
      path: '/api/health/ready'
      fullPath: '/api/health/ready'
      preLoaderRoute: typeof ApiHealthReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/observability/v1/canary': {
      id: '/api/observability/v1/canary'
      path: '/api/observability/v1/canary'
      fullPath: '/api/observability/v1/canary'
      preLoaderRoute: typeof ApiObservabilityV1CanaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/observability/v1/telemetry': {
      id: '/api/observability/v1/telemetry'
      path: '/api/observability/v1/telemetry'
      fullPath: '/api/observability/v1/telemetry'
      preLoaderRoute: typeof ApiObservabilityV1TelemetryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PublicRouteChildren {
  PublicDatenschutzRoute: typeof PublicDatenschutzRoute
  PublicImpressumRoute: typeof PublicImpressumRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicDatenschutzRoute: PublicDatenschutzRoute,
  PublicImpressumRoute: PublicImpressumRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  AktivierenRoute: AktivierenRoute,
  AnmeldenRoute: AnmeldenRoute,
  AppRoute: AppRoute,
  EinrichtenRoute: EinrichtenRoute,
  PasswortVergessenRoute: PasswortVergessenRoute,
  PasswortZuruecksetzenRoute: PasswortZuruecksetzenRoute,
  RegistrierenRoute: RegistrierenRoute,
  AktivierenAbschliessenRoute: AktivierenAbschliessenRoute,
  ApiRpcRoute: ApiRpcRoute,
  OperatorSetupRoute: OperatorSetupRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiHealthLiveRoute: ApiHealthLiveRoute,
  ApiHealthReadyRoute: ApiHealthReadyRoute,
  ApiObservabilityV1CanaryRoute: ApiObservabilityV1CanaryRoute,
  ApiObservabilityV1TelemetryRoute: ApiObservabilityV1TelemetryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
