services:
  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: stu
      POSTGRES_USER: stu
      POSTGRES_DB: stu
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    build:
      context: .
      dockerfile: Dockerfile.rabbitmq
    restart: unless-stopped
    environment:
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbitmq_stream
        advertised_host localhost
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  pulsar:
    image: apachepulsar/pulsar:latest
    restart: unless-stopped
    command: bin/pulsar standalone
    environment: 
      - PULSAR_STANDALONE_USE_ZOOKEEPER=1
    volumes:
      - pulsar_data:/pulsar/data
      - pulsar_config:/pulsar/conf
    
