services:
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: stu
      POSTGRES_USER: stu
      POSTGRES_DB: stu

  rabbitmq:
    build:
      context: .
      dockerfile: Dockerfile.rabbitmq
    restart: unless-stopped
    ports:
      - 15672:15672
    environment:
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbitmq_stream
        advertised_host localhost

  libsql:
    image: ghcr.io/tursodatabase/libsql-server:latest
    ports:
      - 8080:8080
      - 9090:9090
    environment:
      SQLD_NODE: primary
      LIBSQL_ADMIN_AUTH_KEY: admin
      SQLD_ADMIN_LISTEN_ADDR: 0.0.0.0:9090
    command: /bin/sqld --enable-http-console --enable-namespaces
