services:
  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: stu
      POSTGRES_USER: stu
      POSTGRES_DB: stu
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    build:
      context: .
      dockerfile: Dockerfile.rabbitmq
    restart: unless-stopped
    environment:
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbitmq_stream
        advertised_host localhost
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  pulsar:
    image: apachepulsar/pulsar:latest
    restart: unless-stopped
    command: bin/pulsar standalone
    environment: 
      - PULSAR_STANDALONE_USE_ZOOKEEPER=1
    
