FROM node:22
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
ENV TMPDIR="/tmp"
ENV V8_COMPILE_CACHE_CACHE_DIR="/tmp/v8-compile-cache"

RUN corepack enable
RUN pnpm config set store-dir "$PNPM_HOME/store"

WORKDIR /usr/src/app
