import type { KadmosFormat } from "./format";
import type { KadmosSubstitionsPayload } from "./substitutions";

const convertDateToNumber = (date: Date) => {
  return parseInt(
    `${date.getFullYear()}${date.getMonth().toString().padStart(2, "0")}${date.getDate().toString().padStart(2, "0")}`,
  );
};

export const buildSubstitutionsPayload = (
  formatName: string,
  schoolName: string,
  date: Date,
  hideCancelCausedByEvent: boolean,
  format: KadmosFormat,
): KadmosSubstitionsPayload => {
  const {
    dateOffset,
    strikethrough,
    mergeBlocks,
    showOnlyFutureSub,
    showBreakSupervisions,
    showTeacher,
    showClass,
    showHour,
    showInfo,
    showRoom,
    showSubject,
    groupBy,
    hideAbsent,
    departmentIds,
    departmentElementType,
    hideCancelWithSubstitution,
    showTime,
    showSubstText,
    showAbsentElements,
    showAffectedElements,
    showUnitTime,
    showMessages,
    showStudentgroup,
    enableSubstitutionFrom,
    showSubstitutionFrom,
    showTeacherOnEvent,
    showAbsentTeacher,
    strikethroughAbsentTeacher,
    activityTypeIds,
    showEvent,
    showCancel,
    showOnlyCancel,
    showSubstTypeColor,
    showExamSupervision,
    showUnheraldedExams,
  } = format;

  return {
    formatName,
    schoolName,
    date: convertDateToNumber(date),
    dateOffset,
    strikethrough,
    mergeBlocks,
    showOnlyFutureSub,
    showBreakSupervisions,
    showTeacher,
    showClass,
    showHour,
    showInfo,
    showRoom,
    showSubject,
    groupBy,
    hideAbsent,
    departmentIds,
    departmentElementType,
    hideCancelWithSubstitution,
    hideCancelCausedByEvent,
    showTime,
    showSubstText,
    showAbsentElements,
    showAffectedElements,
    showUnitTime,
    showMessages,
    showStudentgroup,
    enableSubstitutionFrom,
    showSubstitutionFrom,
    showTeacherOnEvent,
    showAbsentTeacher,
    strikethroughAbsentTeacher,
    activityTypeIds,
    showEvent,
    showCancel,
    showOnlyCancel,
    showSubstTypeColor,
    showExamSupervision,
    showUnheraldedExams,
  };
};
