/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSchoolsRouteImport } from './routes/admin.schools'
import { Route as AdminPeopleRouteImport } from './routes/admin.people'
import { Route as PublicRoadmapRouteImport } from './routes/_public.roadmap'
import { Route as PublicImpressumRouteImport } from './routes/_public.impressum'
import { Route as PublicDatenschutzRouteImport } from './routes/_public.datenschutz'
import { Route as AdminUsersIndexRouteImport } from './routes/admin.users.index'
import { Route as AdminPeopleIndexRouteImport } from './routes/admin.people.index'
import { Route as AdminUsersNewRouteImport } from './routes/admin.users.new'
import { Route as AdminSchoolsSchoolRouteImport } from './routes/admin.schools.$school'
import { Route as AdminPeopleNewRouteImport } from './routes/admin.people.new'
import { Route as AdminSchoolsSchoolYearsRouteImport } from './routes/admin.schools.$school.years'
import { Route as AdminSchoolsSchoolThemeRouteImport } from './routes/admin.schools.$school.theme'
import { Route as AdminSchoolsSchoolSubstitutionsRouteImport } from './routes/admin.schools.$school.substitutions'
import { Route as AdminSchoolsSchoolYearsIndexRouteImport } from './routes/admin.schools.$school.years.index'
import { Route as AdminSchoolsSchoolYearsNewRouteImport } from './routes/admin.schools.$school.years.new'
import { Route as AdminSchoolsSchoolYearsStartYearRouteImport } from './routes/admin.schools.$school.years.$startYear'
import { Route as AdminSchoolsSchoolYearsStartYearIndexRouteImport } from './routes/admin.schools.$school.years.$startYear.index'
import { Route as AdminSchoolsSchoolYearsStartYearSchedulesRouteImport } from './routes/admin.schools.$school.years.$startYear.schedules'
import { Route as AdminSchoolsSchoolYearsStartYearCoursesRouteImport } from './routes/admin.schools.$school.years.$startYear.courses'
import { Route as AdminSchoolsSchoolYearsStartYearClassesRouteImport } from './routes/admin.schools.$school.years.$startYear.classes'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSchoolsRoute = AdminSchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPeopleRoute = AdminPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AdminRoute,
} as any)
const PublicRoadmapRoute = PublicRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => PublicRoute,
} as any)
const PublicImpressumRoute = PublicImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => PublicRoute,
} as any)
const PublicDatenschutzRoute = PublicDatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => PublicRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminUsersRoute,
} as any)
const AdminPeopleIndexRoute = AdminPeopleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminPeopleRoute,
} as any)
const AdminUsersNewRoute = AdminUsersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminUsersRoute,
} as any)
const AdminSchoolsSchoolRoute = AdminSchoolsSchoolRouteImport.update({
  id: '/$school',
  path: '/$school',
  getParentRoute: () => AdminSchoolsRoute,
} as any)
const AdminPeopleNewRoute = AdminPeopleNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminPeopleRoute,
} as any)
const AdminSchoolsSchoolYearsRoute = AdminSchoolsSchoolYearsRouteImport.update({
  id: '/years',
  path: '/years',
  getParentRoute: () => AdminSchoolsSchoolRoute,
} as any)
const AdminSchoolsSchoolThemeRoute = AdminSchoolsSchoolThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => AdminSchoolsSchoolRoute,
} as any)
const AdminSchoolsSchoolSubstitutionsRoute =
  AdminSchoolsSchoolSubstitutionsRouteImport.update({
    id: '/substitutions',
    path: '/substitutions',
    getParentRoute: () => AdminSchoolsSchoolRoute,
  } as any)
const AdminSchoolsSchoolYearsIndexRoute =
  AdminSchoolsSchoolYearsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminSchoolsSchoolYearsRoute,
  } as any)
const AdminSchoolsSchoolYearsNewRoute =
  AdminSchoolsSchoolYearsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AdminSchoolsSchoolYearsRoute,
  } as any)
const AdminSchoolsSchoolYearsStartYearRoute =
  AdminSchoolsSchoolYearsStartYearRouteImport.update({
    id: '/$startYear',
    path: '/$startYear',
    getParentRoute: () => AdminSchoolsSchoolYearsRoute,
  } as any)
const AdminSchoolsSchoolYearsStartYearIndexRoute =
  AdminSchoolsSchoolYearsStartYearIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminSchoolsSchoolYearsStartYearRoute,
  } as any)
const AdminSchoolsSchoolYearsStartYearSchedulesRoute =
  AdminSchoolsSchoolYearsStartYearSchedulesRouteImport.update({
    id: '/schedules',
    path: '/schedules',
    getParentRoute: () => AdminSchoolsSchoolYearsStartYearRoute,
  } as any)
const AdminSchoolsSchoolYearsStartYearCoursesRoute =
  AdminSchoolsSchoolYearsStartYearCoursesRouteImport.update({
    id: '/courses',
    path: '/courses',
    getParentRoute: () => AdminSchoolsSchoolYearsStartYearRoute,
  } as any)
const AdminSchoolsSchoolYearsStartYearClassesRoute =
  AdminSchoolsSchoolYearsStartYearClassesRouteImport.update({
    id: '/classes',
    path: '/classes',
    getParentRoute: () => AdminSchoolsSchoolYearsStartYearRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/datenschutz': typeof PublicDatenschutzRoute
  '/impressum': typeof PublicImpressumRoute
  '/roadmap': typeof PublicRoadmapRoute
  '/admin/people': typeof AdminPeopleRouteWithChildren
  '/admin/schools': typeof AdminSchoolsRouteWithChildren
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/people/new': typeof AdminPeopleNewRoute
  '/admin/schools/$school': typeof AdminSchoolsSchoolRouteWithChildren
  '/admin/users/new': typeof AdminUsersNewRoute
  '/admin/people/': typeof AdminPeopleIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/schools/$school/substitutions': typeof AdminSchoolsSchoolSubstitutionsRoute
  '/admin/schools/$school/theme': typeof AdminSchoolsSchoolThemeRoute
  '/admin/schools/$school/years': typeof AdminSchoolsSchoolYearsRouteWithChildren
  '/admin/schools/$school/years/$startYear': typeof AdminSchoolsSchoolYearsStartYearRouteWithChildren
  '/admin/schools/$school/years/new': typeof AdminSchoolsSchoolYearsNewRoute
  '/admin/schools/$school/years/': typeof AdminSchoolsSchoolYearsIndexRoute
  '/admin/schools/$school/years/$startYear/classes': typeof AdminSchoolsSchoolYearsStartYearClassesRoute
  '/admin/schools/$school/years/$startYear/courses': typeof AdminSchoolsSchoolYearsStartYearCoursesRoute
  '/admin/schools/$school/years/$startYear/schedules': typeof AdminSchoolsSchoolYearsStartYearSchedulesRoute
  '/admin/schools/$school/years/$startYear/': typeof AdminSchoolsSchoolYearsStartYearIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/datenschutz': typeof PublicDatenschutzRoute
  '/impressum': typeof PublicImpressumRoute
  '/roadmap': typeof PublicRoadmapRoute
  '/admin/schools': typeof AdminSchoolsRouteWithChildren
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminIndexRoute
  '/admin/people/new': typeof AdminPeopleNewRoute
  '/admin/schools/$school': typeof AdminSchoolsSchoolRouteWithChildren
  '/admin/users/new': typeof AdminUsersNewRoute
  '/admin/people': typeof AdminPeopleIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/admin/schools/$school/substitutions': typeof AdminSchoolsSchoolSubstitutionsRoute
  '/admin/schools/$school/theme': typeof AdminSchoolsSchoolThemeRoute
  '/admin/schools/$school/years/new': typeof AdminSchoolsSchoolYearsNewRoute
  '/admin/schools/$school/years': typeof AdminSchoolsSchoolYearsIndexRoute
  '/admin/schools/$school/years/$startYear/classes': typeof AdminSchoolsSchoolYearsStartYearClassesRoute
  '/admin/schools/$school/years/$startYear/courses': typeof AdminSchoolsSchoolYearsStartYearCoursesRoute
  '/admin/schools/$school/years/$startYear/schedules': typeof AdminSchoolsSchoolYearsStartYearSchedulesRoute
  '/admin/schools/$school/years/$startYear': typeof AdminSchoolsSchoolYearsStartYearIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/_public/datenschutz': typeof PublicDatenschutzRoute
  '/_public/impressum': typeof PublicImpressumRoute
  '/_public/roadmap': typeof PublicRoadmapRoute
  '/admin/people': typeof AdminPeopleRouteWithChildren
  '/admin/schools': typeof AdminSchoolsRouteWithChildren
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/_public/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/people/new': typeof AdminPeopleNewRoute
  '/admin/schools/$school': typeof AdminSchoolsSchoolRouteWithChildren
  '/admin/users/new': typeof AdminUsersNewRoute
  '/admin/people/': typeof AdminPeopleIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/schools/$school/substitutions': typeof AdminSchoolsSchoolSubstitutionsRoute
  '/admin/schools/$school/theme': typeof AdminSchoolsSchoolThemeRoute
  '/admin/schools/$school/years': typeof AdminSchoolsSchoolYearsRouteWithChildren
  '/admin/schools/$school/years/$startYear': typeof AdminSchoolsSchoolYearsStartYearRouteWithChildren
  '/admin/schools/$school/years/new': typeof AdminSchoolsSchoolYearsNewRoute
  '/admin/schools/$school/years/': typeof AdminSchoolsSchoolYearsIndexRoute
  '/admin/schools/$school/years/$startYear/classes': typeof AdminSchoolsSchoolYearsStartYearClassesRoute
  '/admin/schools/$school/years/$startYear/courses': typeof AdminSchoolsSchoolYearsStartYearCoursesRoute
  '/admin/schools/$school/years/$startYear/schedules': typeof AdminSchoolsSchoolYearsStartYearSchedulesRoute
  '/admin/schools/$school/years/$startYear/': typeof AdminSchoolsSchoolYearsStartYearIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/datenschutz'
    | '/impressum'
    | '/roadmap'
    | '/admin/people'
    | '/admin/schools'
    | '/admin/users'
    | '/admin/'
    | '/admin/people/new'
    | '/admin/schools/$school'
    | '/admin/users/new'
    | '/admin/people/'
    | '/admin/users/'
    | '/admin/schools/$school/substitutions'
    | '/admin/schools/$school/theme'
    | '/admin/schools/$school/years'
    | '/admin/schools/$school/years/$startYear'
    | '/admin/schools/$school/years/new'
    | '/admin/schools/$school/years/'
    | '/admin/schools/$school/years/$startYear/classes'
    | '/admin/schools/$school/years/$startYear/courses'
    | '/admin/schools/$school/years/$startYear/schedules'
    | '/admin/schools/$school/years/$startYear/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/datenschutz'
    | '/impressum'
    | '/roadmap'
    | '/admin/schools'
    | '/'
    | '/admin'
    | '/admin/people/new'
    | '/admin/schools/$school'
    | '/admin/users/new'
    | '/admin/people'
    | '/admin/users'
    | '/admin/schools/$school/substitutions'
    | '/admin/schools/$school/theme'
    | '/admin/schools/$school/years/new'
    | '/admin/schools/$school/years'
    | '/admin/schools/$school/years/$startYear/classes'
    | '/admin/schools/$school/years/$startYear/courses'
    | '/admin/schools/$school/years/$startYear/schedules'
    | '/admin/schools/$school/years/$startYear'
  id:
    | '__root__'
    | '/_public'
    | '/admin'
    | '/login'
    | '/_public/datenschutz'
    | '/_public/impressum'
    | '/_public/roadmap'
    | '/admin/people'
    | '/admin/schools'
    | '/admin/users'
    | '/_public/'
    | '/admin/'
    | '/admin/people/new'
    | '/admin/schools/$school'
    | '/admin/users/new'
    | '/admin/people/'
    | '/admin/users/'
    | '/admin/schools/$school/substitutions'
    | '/admin/schools/$school/theme'
    | '/admin/schools/$school/years'
    | '/admin/schools/$school/years/$startYear'
    | '/admin/schools/$school/years/new'
    | '/admin/schools/$school/years/'
    | '/admin/schools/$school/years/$startYear/classes'
    | '/admin/schools/$school/years/$startYear/courses'
    | '/admin/schools/$school/years/$startYear/schedules'
    | '/admin/schools/$school/years/$startYear/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/schools': {
      id: '/admin/schools'
      path: '/schools'
      fullPath: '/admin/schools'
      preLoaderRoute: typeof AdminSchoolsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/people': {
      id: '/admin/people'
      path: '/people'
      fullPath: '/admin/people'
      preLoaderRoute: typeof AdminPeopleRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/roadmap': {
      id: '/_public/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof PublicRoadmapRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/impressum': {
      id: '/_public/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof PublicImpressumRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/datenschutz': {
      id: '/_public/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof PublicDatenschutzRouteImport
      parentRoute: typeof PublicRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/admin/people/': {
      id: '/admin/people/'
      path: '/'
      fullPath: '/admin/people/'
      preLoaderRoute: typeof AdminPeopleIndexRouteImport
      parentRoute: typeof AdminPeopleRoute
    }
    '/admin/users/new': {
      id: '/admin/users/new'
      path: '/new'
      fullPath: '/admin/users/new'
      preLoaderRoute: typeof AdminUsersNewRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/admin/schools/$school': {
      id: '/admin/schools/$school'
      path: '/$school'
      fullPath: '/admin/schools/$school'
      preLoaderRoute: typeof AdminSchoolsSchoolRouteImport
      parentRoute: typeof AdminSchoolsRoute
    }
    '/admin/people/new': {
      id: '/admin/people/new'
      path: '/new'
      fullPath: '/admin/people/new'
      preLoaderRoute: typeof AdminPeopleNewRouteImport
      parentRoute: typeof AdminPeopleRoute
    }
    '/admin/schools/$school/years': {
      id: '/admin/schools/$school/years'
      path: '/years'
      fullPath: '/admin/schools/$school/years'
      preLoaderRoute: typeof AdminSchoolsSchoolYearsRouteImport
      parentRoute: typeof AdminSchoolsSchoolRoute
    }
    '/admin/schools/$school/theme': {
      id: '/admin/schools/$school/theme'
      path: '/theme'
      fullPath: '/admin/schools/$school/theme'
      preLoaderRoute: typeof AdminSchoolsSchoolThemeRouteImport
      parentRoute: typeof AdminSchoolsSchoolRoute
    }
    '/admin/schools/$school/substitutions': {
      id: '/admin/schools/$school/substitutions'
      path: '/substitutions'
      fullPath: '/admin/schools/$school/substitutions'
      preLoaderRoute: typeof AdminSchoolsSchoolSubstitutionsRouteImport
      parentRoute: typeof AdminSchoolsSchoolRoute
    }
    '/admin/schools/$school/years/': {
      id: '/admin/schools/$school/years/'
      path: '/'
      fullPath: '/admin/schools/$school/years/'
      preLoaderRoute: typeof AdminSchoolsSchoolYearsIndexRouteImport
      parentRoute: typeof AdminSchoolsSchoolYearsRoute
    }
    '/admin/schools/$school/years/new': {
      id: '/admin/schools/$school/years/new'
      path: '/new'
      fullPath: '/admin/schools/$school/years/new'
      preLoaderRoute: typeof AdminSchoolsSchoolYearsNewRouteImport
      parentRoute: typeof AdminSchoolsSchoolYearsRoute
    }
    '/admin/schools/$school/years/$startYear': {
      id: '/admin/schools/$school/years/$startYear'
      path: '/$startYear'
      fullPath: '/admin/schools/$school/years/$startYear'
      preLoaderRoute: typeof AdminSchoolsSchoolYearsStartYearRouteImport
      parentRoute: typeof AdminSchoolsSchoolYearsRoute
    }
    '/admin/schools/$school/years/$startYear/': {
      id: '/admin/schools/$school/years/$startYear/'
      path: '/'
      fullPath: '/admin/schools/$school/years/$startYear/'
      preLoaderRoute: typeof AdminSchoolsSchoolYearsStartYearIndexRouteImport
      parentRoute: typeof AdminSchoolsSchoolYearsStartYearRoute
    }
    '/admin/schools/$school/years/$startYear/schedules': {
      id: '/admin/schools/$school/years/$startYear/schedules'
      path: '/schedules'
      fullPath: '/admin/schools/$school/years/$startYear/schedules'
      preLoaderRoute: typeof AdminSchoolsSchoolYearsStartYearSchedulesRouteImport
      parentRoute: typeof AdminSchoolsSchoolYearsStartYearRoute
    }
    '/admin/schools/$school/years/$startYear/courses': {
      id: '/admin/schools/$school/years/$startYear/courses'
      path: '/courses'
      fullPath: '/admin/schools/$school/years/$startYear/courses'
      preLoaderRoute: typeof AdminSchoolsSchoolYearsStartYearCoursesRouteImport
      parentRoute: typeof AdminSchoolsSchoolYearsStartYearRoute
    }
    '/admin/schools/$school/years/$startYear/classes': {
      id: '/admin/schools/$school/years/$startYear/classes'
      path: '/classes'
      fullPath: '/admin/schools/$school/years/$startYear/classes'
      preLoaderRoute: typeof AdminSchoolsSchoolYearsStartYearClassesRouteImport
      parentRoute: typeof AdminSchoolsSchoolYearsStartYearRoute
    }
  }
}

interface PublicRouteChildren {
  PublicDatenschutzRoute: typeof PublicDatenschutzRoute
  PublicImpressumRoute: typeof PublicImpressumRoute
  PublicRoadmapRoute: typeof PublicRoadmapRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicDatenschutzRoute: PublicDatenschutzRoute,
  PublicImpressumRoute: PublicImpressumRoute,
  PublicRoadmapRoute: PublicRoadmapRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface AdminPeopleRouteChildren {
  AdminPeopleNewRoute: typeof AdminPeopleNewRoute
  AdminPeopleIndexRoute: typeof AdminPeopleIndexRoute
}

const AdminPeopleRouteChildren: AdminPeopleRouteChildren = {
  AdminPeopleNewRoute: AdminPeopleNewRoute,
  AdminPeopleIndexRoute: AdminPeopleIndexRoute,
}

const AdminPeopleRouteWithChildren = AdminPeopleRoute._addFileChildren(
  AdminPeopleRouteChildren,
)

interface AdminSchoolsSchoolYearsStartYearRouteChildren {
  AdminSchoolsSchoolYearsStartYearClassesRoute: typeof AdminSchoolsSchoolYearsStartYearClassesRoute
  AdminSchoolsSchoolYearsStartYearCoursesRoute: typeof AdminSchoolsSchoolYearsStartYearCoursesRoute
  AdminSchoolsSchoolYearsStartYearSchedulesRoute: typeof AdminSchoolsSchoolYearsStartYearSchedulesRoute
  AdminSchoolsSchoolYearsStartYearIndexRoute: typeof AdminSchoolsSchoolYearsStartYearIndexRoute
}

const AdminSchoolsSchoolYearsStartYearRouteChildren: AdminSchoolsSchoolYearsStartYearRouteChildren =
  {
    AdminSchoolsSchoolYearsStartYearClassesRoute:
      AdminSchoolsSchoolYearsStartYearClassesRoute,
    AdminSchoolsSchoolYearsStartYearCoursesRoute:
      AdminSchoolsSchoolYearsStartYearCoursesRoute,
    AdminSchoolsSchoolYearsStartYearSchedulesRoute:
      AdminSchoolsSchoolYearsStartYearSchedulesRoute,
    AdminSchoolsSchoolYearsStartYearIndexRoute:
      AdminSchoolsSchoolYearsStartYearIndexRoute,
  }

const AdminSchoolsSchoolYearsStartYearRouteWithChildren =
  AdminSchoolsSchoolYearsStartYearRoute._addFileChildren(
    AdminSchoolsSchoolYearsStartYearRouteChildren,
  )

interface AdminSchoolsSchoolYearsRouteChildren {
  AdminSchoolsSchoolYearsStartYearRoute: typeof AdminSchoolsSchoolYearsStartYearRouteWithChildren
  AdminSchoolsSchoolYearsNewRoute: typeof AdminSchoolsSchoolYearsNewRoute
  AdminSchoolsSchoolYearsIndexRoute: typeof AdminSchoolsSchoolYearsIndexRoute
}

const AdminSchoolsSchoolYearsRouteChildren: AdminSchoolsSchoolYearsRouteChildren =
  {
    AdminSchoolsSchoolYearsStartYearRoute:
      AdminSchoolsSchoolYearsStartYearRouteWithChildren,
    AdminSchoolsSchoolYearsNewRoute: AdminSchoolsSchoolYearsNewRoute,
    AdminSchoolsSchoolYearsIndexRoute: AdminSchoolsSchoolYearsIndexRoute,
  }

const AdminSchoolsSchoolYearsRouteWithChildren =
  AdminSchoolsSchoolYearsRoute._addFileChildren(
    AdminSchoolsSchoolYearsRouteChildren,
  )

interface AdminSchoolsSchoolRouteChildren {
  AdminSchoolsSchoolSubstitutionsRoute: typeof AdminSchoolsSchoolSubstitutionsRoute
  AdminSchoolsSchoolThemeRoute: typeof AdminSchoolsSchoolThemeRoute
  AdminSchoolsSchoolYearsRoute: typeof AdminSchoolsSchoolYearsRouteWithChildren
}

const AdminSchoolsSchoolRouteChildren: AdminSchoolsSchoolRouteChildren = {
  AdminSchoolsSchoolSubstitutionsRoute: AdminSchoolsSchoolSubstitutionsRoute,
  AdminSchoolsSchoolThemeRoute: AdminSchoolsSchoolThemeRoute,
  AdminSchoolsSchoolYearsRoute: AdminSchoolsSchoolYearsRouteWithChildren,
}

const AdminSchoolsSchoolRouteWithChildren =
  AdminSchoolsSchoolRoute._addFileChildren(AdminSchoolsSchoolRouteChildren)

interface AdminSchoolsRouteChildren {
  AdminSchoolsSchoolRoute: typeof AdminSchoolsSchoolRouteWithChildren
}

const AdminSchoolsRouteChildren: AdminSchoolsRouteChildren = {
  AdminSchoolsSchoolRoute: AdminSchoolsSchoolRouteWithChildren,
}

const AdminSchoolsRouteWithChildren = AdminSchoolsRoute._addFileChildren(
  AdminSchoolsRouteChildren,
)

interface AdminUsersRouteChildren {
  AdminUsersNewRoute: typeof AdminUsersNewRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminUsersRouteChildren: AdminUsersRouteChildren = {
  AdminUsersNewRoute: AdminUsersNewRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminUsersRouteWithChildren = AdminUsersRoute._addFileChildren(
  AdminUsersRouteChildren,
)

interface AdminRouteChildren {
  AdminPeopleRoute: typeof AdminPeopleRouteWithChildren
  AdminSchoolsRoute: typeof AdminSchoolsRouteWithChildren
  AdminUsersRoute: typeof AdminUsersRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminPeopleRoute: AdminPeopleRouteWithChildren,
  AdminSchoolsRoute: AdminSchoolsRouteWithChildren,
  AdminUsersRoute: AdminUsersRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
