#!/bin/bash

cd apps/flutter

while test $# != 0
do
    case "$1" in
    --clean)
        flutter clean ;;
    esac
    shift
done

flutter build appbundle --obfuscate --split-debug-info ./debug-symbols
flutter build ipa --obfuscate --split-debug-info ./debug-symbols
