#!/bin/bash

set -eu

cd apps/flutter

while test $# != 0
do
    case "$1" in
    --clean)
        flutter clean ;;
    esac
    shift
done

flutter build appbundle --obfuscate --split-debug-info ./debug-symbols
open build/app/outputs/bundle/release

flutter build ipa --obfuscate --split-debug-info ./debug-symbols
open build/ios/archive/Runner.xcarchive

set -a
source .env
flutter packages pub run sentry_dart_plugin
