#!/bin/bash

set -eau
. .env

# Check if required arguments are provided
if [ $# -lt 1 ]; then
  echo "Usage: $0 <deployment-name> [src-dir] [builds-dir]"
  exit 1
fi

# Variables
DEPLOYMENT_NAME="${1}"
SRC_DIR="${2:-src}"
BUILDS_DIR="${3:-builds}"

cd $SRC_DIR

# Build
pnpm install
pnpm db:deploy
pnpm --filter nextjs build

# Deploy
BUILD_ID="$(date +%s)-$(git rev-parse HEAD)"
BUILD_PATH="$BUILDS_DIR/$BUILD_ID"

cd ..

mkdir -p "$BUILD_PATH/_next"

mv "$SRC_DIR/apps/nextjs/.next/standalone" "$BUILD_PATH/server"
mv "$SRC_DIR/apps/nextjs/.next/static" "$BUILD_PATH/_next/static"
cp -r "$SRC_DIR/apps/nextjs/public" "$BUILD_PATH/public"

rm "$DEPLOYMENT_NAME"
ln -s "$BUILD_PATH" "$DEPLOYMENT_NAME"

pm2 reload "$DEPLOYMENT_NAME"
