#!/bin/bash

source .venv/bin/activate
set -o allexport; source .env; set +o allexport

SCRIPT_NAME=$1
SCRIPT_PATH="apps/scripts/src/$SCRIPT_NAME"

if [ ! -f "$SCRIPT_PATH" ]; then
    echo "File $SCRIPT_PATH does not exist"
    exit 1
fi

if [[ $SCRIPT_NAME == *".ts" ]]; then
    ts-node $SCRIPT_PATH $@
elif [[ $SCRIPT_NAME == *".py" ]]; then
    shift
    python $SCRIPT_PATH $@
else
    echo "Unknown file type"
fi
