#!/bin/bash

set -eau
. .env

python3 -m venv .venv
source .venv/bin/activate
pip install -r requirements.txt

# If the --docker flag is passed, run the following commands
# if [[ "$1" == "--docker" ]]; then
#     docker compose up -d
# fi
while test $# != 0
do
    case "$1" in
    --docker) docker compose up -d ;;
    --) shift; break;;
    *)  usage ;;
    esac
    shift
done


pnpm install
pnpm build:internal
pnpm db:push

scripts/console seed igs-lil
